### ISSUE TITLE
Tag searching no longer matches inherited tags

### ISSUE THREAD

**Issue by valentinesd** [SpriteLink/NIPAP#1055]
We recently upgraded from 0.28.4 to 0.29.3.  When searching using the web interface or pynipap's Prefix.smart_search, the tag search (string prefixed by #) no longer matches prefixes that have inherited the tag.

**Comment by garberg** [comment]
Confirmed, the smart parser introduced in v0.29.0 does not create a query to match tags to inherited tags, as it should. Thanks for pointing it out!
