### ISSUE TITLE
The demo installation is not working

### ISSUE THREAD

**Issue by peterpakos** [SpriteLink/NIPAP#1063]
When attempting to log in as demo/demo at http://nipap-demo.spritelink.net/ I get "Internal Server Error" message:

![screen shot 2016-09-28 at 16 32 24](https://cloud.githubusercontent.com/assets/8777471/18920447/47751efa-8599-11e6-9351-3825d31c817c.png)

**Comment by garberg** [comment]
Thanks for letting us know! Now it should be back in business.
