### ISSUE TITLE
smart_result['error'] KeyError 

### ISSUE THREAD

**Issue by alanwill** [SpriteLink/NIPAP#1094]
I'm getting the following error when doing any smart_searches but this used to work

```
>>> search_result = Prefix.smart_search('127.0.0.0/8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pynipap.py", line 1103, in smart_search
    result['error'] = smart_result['error']
KeyError: 'error'
>>>
```

any idea what could be causing this all of a sudden?

**Comment by plajjan** [comment]
What's your version of nipapd and python-pynipap ? This is a new key so pynipap 0.29.4 will expect it to be there. If you run an older backend it will not populate it.

**Comment by alanwill** [comment]
pynipap (0.29.5) and nipapd version: 0.29.5

**Comment by alanwill** [comment]
Could this possibly be related to data in Postgres? From the UI I can browse VRFs and Pools just not Prefixes so I'm wondering if we may have entered data which (extra ` or ' or " or ,) that broke things?

**Comment by daneb** [comment]
We were having a similar issue when searching for MAC addresses (:node field) that were prepended with "00:". How we **resolved** this was adding escaped double quotes to each Prefix Smart Search. I would love to understand why I needed to do this....... ?

**Comment by plajjan** [comment]
@alanwill aha, so it would seem it is related to the data you have stored.. which feels super weird :/ We've seen this in the past with encoding errors. Is the nipap database in UTF-8 ? We shouldn't be sensitive to misplaced quotation characters... regardless I think you would need to try to find the prefix that is causing the error. 

@daneb uh, you should open an issue for that. Can you reproduce on nipap-demo.spritelink.net ?

**Comment by plajjan** [comment]
@alanwill can you try to run the query you showed in the original question but with max_result=1 and increment it until you hit the error? Maybe that will help you nail down the error.

**Comment by alanwill** [comment]
@plajjan that didn't seem to help much unfortunately :-/

```
>>> search_result = Prefix.smart_search('127.0.0.0/8', {'max_result':1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pynipap.py", line 1103, in smart_search
    result['error'] = smart_result['error']
KeyError: 'error'
```

**Comment by alanwill** [comment]
For what it's worth I took a peek at the DB and only the ip_net_plan and ip_net_log tables have data in them and in the ip_net_plan table there's nothing that looked like bad data at all.

**Comment by alanwill** [comment]
@daneb in your case the application isn't throwing the keyerror so that sounds like an unrelated issue.

**Comment by daneb** [comment]
Thanks @Alan i will open a separate issue

www.danebalia.com
www.codedtrue.com




On Tue, Nov 8, 2016 at 11:58 PM +0200, "Alan Williams" <notifications@github.com> wrote:












@daneb in your case the application isn't throwing the keyerror so that sounds like an unrelated issue.

**Comment by alanwill** [comment]
ping @plajjan any other pointers you can provide to get past that KeyError?

**Comment by mylex666** [comment]
I have the same error with the smart_search, the normal search works though. 

 search_result = Prefix.smart_search('10.32.0.0/16', {'max_result':1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pynipap.py", line 1103, in smart_search
    result['error'] = smart_result['error']
KeyError: 'error'

**Comment by alanwill** [comment]
I was finally able to resolve this error by running `apt-get dist-upgrade` on the host. There was clearly something missing that it pulled down. Oddly enough the version numbers stayed the same even after the upgrade but the problem is gone so that part of the mystery might remain unsolved.
