### ISSUE TITLE
Old documentation

### ISSUE THREAD

**Issue by emil-nasso** [SpriteLink/NIPAP#1099]
My standard way of finding everything is google (im lazy. :) ).

When looking for the nipap documentation i found it here:
https://www.google.se/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=nipap%20documentation

First link goes here: http://nipap-plajjan.readthedocs.io/en/latest/nipap.html

There were some stuff in the documentation that didn't make sense and i couldn't find any of the versions i found on github.

This seems to be the right place to read the documentation: 
http://nipap.readthedocs.io/en/latest/

Can anything be done about this? Or maybe I'm the only one being confused about this. Maybe remove the nipap-plajjan documentation?

**Comment by plajjan** [comment]
Hmpf, too bad google lists it at the top.. 

I used a separate page on RTD to test out some of the documentation generation code and so forth.. don't need it now so I've removed it. Hope Google updates soon :)

**Comment by emil-nasso** [comment]
The real documentation is the third result, so it's not really a biggie. The link still seems to work but maybe it takes a while for the documentation to be removed?

**Comment by plajjan** [comment]
http://nipap-plajjan.readthedocs.io/en/latest/nipap.html returns an error now. Still listed at top of Google but I guess it'll converge at some point. At least now, with an error showing up, users will likely go to the next search result instead of looking at old docs.

**Comment by emil-nasso** [comment]
Can confirm that it was gone from google when i searched today. :)
