### ISSUE TITLE
Would it be okay to publish https://github.com/SpriteLink/NIPAP/tree/master/nipap in pypi?

### ISSUE THREAD

**Issue by bbaja42** [SpriteLink/NIPAP#1102]
Hi, I'm considering using a part of nipap project, where it would make sense to my usecase to depend just on https://github.com/SpriteLink/NIPAP/tree/master/nipap.

Would it be okay if I publish just this part as a pypi package; I see there is already a client package, but for my use case backend package would be useful as well.
I'm happy to do the actual work of publishing, and setting up; and then pass the credentials to you guys.

**Comment by plajjan** [comment]
I am really curious about your use case for this :) You want to import the backend but not actually run the backend? What on earth are you doing? :P

**Comment by bbaja42** [comment]
:D 
Well, I want to import backend, but not actually use it in daemon; instead import it directly in process ( which also doesn't use XML RPC).

**Comment by plajjan** [comment]
Are you trying to integrate NIPAP with another system but instead of doing this over the APIs you want to meld together the code bases?

**Comment by bbaja42** [comment]
Something like that:
A flask process, with auth; that takes requests over rest interface; and calls backend.py ( after translating the requests into something that backend.py understands)

**Comment by plajjan** [comment]
So you want to add a REST API to NIPAP instead of XML-RPC? Why not just integrate it? Also see #570

**Comment by plajjan** [comment]
The separation of backend.py (with all the logic) from xmlrpc.py (with the XML-RPC API) was created for exactly this reason.

**Comment by bbaja42** [comment]
That is the end goal ( full rest interface, where website and client can use it as well) , we still need to see what is the process to contribute back the work :)

**Comment by plajjan** [comment]
But putting backend.py in pypi and building your rest-api.py outside of NIPAP sounds like the wrong way to go.

Instead create a rest_api.py instead in the NIPAP git repo. You can develop it on a git branch until you are ready to push it upstream as a PR. Add some config options to nipapd so it's possible to enable / disable the XML-RPC & REST API independently and.. voila! :)

**Comment by bbaja42** [comment]
Good point, I'll check with colleagues what is the simplest way to merge it upstream ( they did most of work) , thnx for the feedback.

**Comment by bbaja42** [comment]
Wasn't able to make progress on this :(
So closing the issue.
