### ISSUE TITLE
Searching for 'ord' results in an error

### ISSUE THREAD

**Issue by emil-nasso** [SpriteLink/NIPAP#1112]
A picture is worth a thousand words. (I was trying to search by order_id)

![https://dl.dropboxusercontent.com/s/3bzl12bo02idrpu/2016-12-01%20at%2008.27.png](https://dl.dropboxusercontent.com/s/3bzl12bo02idrpu/2016-12-01%20at%2008.27.png)

**Comment by plajjan** [comment]
Yupp, dupe of #1054 though ;) so closing this one..
