### ISSUE TITLE
Saved search URLs are broken since upgrade from 0.28.4 to 0.29

### ISSUE THREAD

**Issue by gburjan** [SpriteLink/NIPAP#1115]
In the former version (nipap-www 0.28.4) when we did a search on the web UI and saved its link, it worked again after opening it in another browser window. This behaviour changed after the upgrade. I think that this can be caused by the modification introduced in this changeset:

https://github.com/SpriteLink/NIPAP/blob/57834938ba84587ceaa07ac4ec901139890add70/nipap-www/nipapwww/public/nipap.js

Regarding to the git log message, the only change is that an extra slash is inserted before query_string, but if we modify the formerly saved

  https://ipam.company.com/prefix/list#query_string=stringToSearch&search_opt_parent=undefined&search_opt_child=undefined&explicit=true

style URLs to 

  https://ipam.company.com/prefix/list#/query_string=stringToSearch&search_opt_parent=undefined&search_opt_child=undefined&explicit=true

it simply omits the specified "stringToSearch" argument and lists all prefixes.

**Comment by garberg** [comment]
Probably related to #1089.
