### ISSUE TITLE
nipap-cli doesn't see the 'global' section in .nipaprc file while parsing config

### ISSUE THREAD

**Issue by maxymax68** [SpriteLink/NIPAP#1116]
nipap-cli doesn't see the 'global' section in .nipaprc file while parsing config

nipap address list FOO

Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 1135, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'global'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nipap", line 124, in <module>
    cmd.exe(cmd.arg, cmd.exe_options, args)
  File "/usr/lib/python3/dist-packages/nipap_cli/nipap_cli.py", line 507, in list_prefix
    v = get_vrf(opts.get('vrf_rt'), default_var='default_list_vrf_rt', abort=True)
  File "/usr/lib/python3/dist-packages/nipap_cli/nipap_cli.py", line 128, in get_vrf
    vrf_rt = cfg.get('global', default_var)
  File "/usr/lib/python3.5/configparser.py", line 778, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.5/configparser.py", line 1138, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'global'

**Comment by plajjan** [comment]
Difficult to troubleshoot without seeing the config file - please post your .nipaprc (just censor passwords) :)

**Comment by maxymax68** [comment]
Hi Kristian,

Here is the contents of my .nipaprc file:

# --------------------------------------
# NIPAP shell command configuration file
# --------------------------------------
#
# This file contains configuration for the NIPAP shell command. The 'nipap'
# executable will look for its config in ~/.nipaprc, so to successfully
# configure NIPAP, this file should be palced there and modified for your
# setup.
#

[global]

# NIPAP connection settings
hostname = 127.0.0.1
port = 1337
username = nipap-www
password = xxxxxxx

# Specify a command which can be used to complete node hostnames. This will be
# called when trying to complete a node hostname.
#
# The string "%search_string%" will be replaced by the current search string.
#complete_node_cmd = node list %search_string%

# Used as default VRF RT by 'nipap address add/modify/remove/view' commands
# when no other VRF RT is specified on the command line. Also used as default
# VRF when expanding a pool with a new prefix for the first time.
# '-' means VRF 'Default' (RT: -)
default_vrf_rt = -

# 'nipap address list' will per default search in the following VRF RT when no
# VRF RT is specified on the command line.
# 'all' means that searches will include results from all VRFs
default_list_vrf_rt = all

# Specify custom columns for 'nipap address list' using a comma separated list
# of columns. If the list is prefixed with '+' it will add these columns in
# addition to the standard set of columns.
#
# Example to list prefix usage statistics in addition to standard columns:
#
#   prefix_list_columns = +total_addresses,used_addresses,free_addresses
#
# Example to only listen VRF RT and prefix:
#
#   prefix_list_columns = vrf_rt,prefix

**Comment by maxymax68** [comment]
Better sent as attached file



[nipaprc.txt](https://github.com/SpriteLink/NIPAP/files/651111/nipaprc.txt)

**Comment by plajjan** [comment]
I just edited your comment, you can use three back-ticks to make pasted code/configs look much better :)

Are you sure you are running `nipap` as the correct user, i.e. you are not using `sudo` or anything to assume another user, thus reading a different `.nipaprc`?

BTW, try not to use the nipap-www user - you should set up a separate user for yourself :)

**Comment by maxymax68** [comment]
I changed the owner of the .nipaprc file and it is working fine now.
Many thanks,
\Max

**Comment by plajjan** [comment]
Aha, interesting, so if .nipaprc is owned by someone else it borks out!? We do check if we can open the file and if the permissions are right... but don't check who the owner is.

**Comment by plajjan** [comment]
Fixed by #1143 - closing.
