### ISSUE TITLE
nipapd fails to install database when db name is not "nipap"

### ISSUE THREAD

**Issue by taktv6** [SpriteLink/NIPAP#1159]
Hi there,

we've got the following problem:

`
 takt@fuckup ~ % docker run -e "DB_HOST=FOOBAR" -e "DB_NAME=nipap_dev" -e "DB_USERNAME=nipap_dev" -e "DB_PASSWORD=XXXXX" -e "NIPAP_USERNAME=nipap" -e "NIPAP_PASSWORD=password" nipap/nipapd:master
Creating user 'nipap'
Added user nipap to database /etc/nipap/local_auth.db
2017-06-07 16:03:51,240: backend    ERROR    Unable to execute query: must be owner of database nipap
...[repeated]...
2017-06-07 16:03:53,079: backend    ERROR    pgsql: FATAL:  remaining connection slots are reserved for non-replication superuser and rds_superuser connections
`

On the same DB server we have a database "nipap" with user "nipap" which works perfectly fine.
I suspect the container is ignoring the DB_NAME environment variable.

Database nipap is owner by user nipap.
Database nipap_dev is owner by nipap_dev.

Thanks
takt

**Comment by taktv6** [comment]
The issue seems to be in nipap/nipap/db_schema.py:
`COMMENT ON DATABASE nipap IS 'NIPAP database - schema version: 6';` etc.

**Comment by plajjan** [comment]
Fixed by #1160, so closing.
