### ISSUE TITLE
After Web UI login, Error Incorrect Username or password on every operation

### ISSUE THREAD

**Issue by djwaterford** [SpriteLink/NIPAP#1161]
Ubuntu 16.04 LTS
root@nipap:~# dpkg -l |grep nipap
ii  nipap-cli                            0.29.6-1                                   all          Neat IP Address Planner
ii  nipap-common                         0.29.6-1                                   all          Neat IP Address Planner
ii  nipap-www                            0.29.6-1                                   all          web frontend for NIPAP
ii  nipapd                               0.29.6-1                                   all          Neat IP Address Planner XML-RPC daemon
ii  python-pynipap                       0.29.6-1                                   all          Python module for accessing NIPAP
ii  python3-pynipap                      0.29.6-1                                   all          Python 3 module for accessing NIPAP

Every operation produces an error popup, Error Incorrect Username or Password.
When running the nipap=passwd test-user command for the user, ther is no error.

**Comment by djwaterford** [comment]
Decided to go with phpipam instead.....

**Comment by plajjan** [comment]
Okay, sorry to hear :/

You probably have an inconsistency between the password for the backend and what the web ui is configured to use...
