### ISSUE TITLE
Performance issue - updates on ip_net_plan causing too much bloat

### ISSUE THREAD

**Issue by elodie-ferreira** [SpriteLink/NIPAP#1169]
Hi.
I've been using NIPAP for IPAM for about a year in a context of an enterprise application for SIM cards management. We have a few clients already and growing, and we've been dealing with issues about NIPAP performance every time a client wants do manage its data.
After a really thorough investigation we came to the conclusion that our major problem is related to the amount of bloat in table ip_net_plan.

Currently we have a bit more than 50k rows in ip_net_plan and clients demanding the allocation/modification of around 5k or more IP addresses each time. After analyzing all triggers executed on a update on ip_net_plan we calculated that for those 5k modifications we have around 40k updates on ip_net_plan. Those 5k IPs are assigned on a /16 range prefix, so, some of those updates are executed (worst case scenario) on around 65.500 rows (cause you have to update column children for each row). After a while of starting to process those 5k the amount of time each SIM card takes to be modified increases brutally.

We already have a cron job executing a vacuum full on ip_net_plan every 30minutes, but executing this procedure seems to be more and more like trying to fix a big open wound with a little band aid.

Any other suggestion?
Is NIPAP ready to deal with this amount of requests/rows/growing demand?
Any future improvement on NIPAP database schema to address the children column in another way?

Thanx

**Comment by eloferreira** [comment]
Btw, we are using NIPAP 0.28.4 version.
