### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by CodingSpiderFox** [SpriteLink/NIPAP#1174]
Is this project still actively maintained? I'm looking for an IPAM solution but I saw that there are pretty old pull requests still open here. I only want to use software that is actively maintained.

**Comment by plajjan** [comment]
I suppose it's somewhat on the back burner, mostly as the current feature set fulfills the needs of the largest users (a couple of ISPs with relatively large installations).

**Comment by CodingSpiderFox** [comment]
Ok. Thanks
