### ISSUE TITLE
XMLRPC error

### ISSUE THREAD

**Issue by Chicago-Stephen** [SpriteLink/NIPAP#1197]
I was following this installation guide http://spritelink.github.io/NIPAP/docs/config-www.html.  However, when trying to run this command "xmlrpc_uri = http://nipap-www@local:s3cret@127.0.0.1:1337" without the quotes, I received an error, "-su: xmlrpc_uri: command not found.

Help please.....

**Comment by garberg** [comment]
Hi, it's not a shell command but a configuration parameter to set in /etc/nipap/nipap.conf. I'll update the documentation to state this clearly.

**Comment by Chicago-Stephen** [comment]
Oh ' okay thank you very much!  :)
