### ISSUE TITLE
/etc/nipap/nipap.conf more than one external ldap auth backend

### ISSUE THREAD

**Issue by ant0nwax** [SpriteLink/NIPAP#1199]
how to use for example

default_backend ldap1,ldap2 both ldaps?

we would like to workaround the following issue:

our users are in different base_dn's

thanks a lot

**Comment by garberg** [comment]
Unfortunately, you cannot specify two default auth backends.

If the users themselves are aware, they can select what auth backend to use by suffixing their username with the name of it: To authenticate the user `foo` using auth backend `ldap1`, use the username `foo@ldap1`. That'll make sure the request is handled by the correct auth backend.

**Comment by ant0nwax** [comment]
Thanks, this is great, I actually missed to answer this, it is already implemented, I also found this solution by digging in the source code and somewhere there in the beginning of the source code is the information in remarks, that the authentication domain can be added by @authdomain after the username... wow what a great documentation for users that are not developers... I will close this case, hope it might help someone because search engines do not find the code remarks, maybe they will find this closed issue, please mark it as solved
