### ISSUE TITLE
Search is too quick when typing

### ISSUE THREAD

**Issue by hallinde** [SpriteLink/NIPAP#1208]
This is a badly described issue. 

Search is trying to find what users type too quick and ends up prolonging the search. Most of the time our users know what equipment they want to look at and now write the name somewhere else and then paste the full name as a workaround as typing ends up being slower.

A way to disable autocomplete?

**Comment by steffenschumacher** [comment]
Check out:
```
grep -B6 -A3 'function .*SearchKey\(\)' /usr/lib/python2.7/dist-packages/nipapwww/public/nipap.js
/*
 * Wrapper for pacing our searches somewhat
 *
 * 200ms works out to be a pretty good delay for a fast typer
 */
function prefixSearchKey() {
	clearTimeout(search_key_timeout);
	search_key_timeout = setTimeout(function() { performPrefixSearch(false) }, 800);
}
--
 * Wrapper for pacing our searches somewhat
 *
 * 200ms works out to be a pretty good delay for a fast typer
 *
 * TODO: merge with prefixSearchKey
 */
function vrfSearchKey() {
	clearTimeout(search_key_timeout);
	search_key_timeout = setTimeout("performVRFSelectorSearch()", 200);
}
```
(I've increased delay to 800 ms)

**Comment by garberg** [comment]
Agreed, I've heard that from other users as well. What seems to be a decent number? I found 500 a good compromise, but I'm open for other suggestions?

**Comment by steffenschumacher** [comment]
Hmm can’t easily make it configurable - half a sec should be ok.
