### ISSUE TITLE
JavaScript library updates not in nipap stable version

### ISSUE THREAD

**Issue by mariahaider** [SpriteLink/NIPAP#1210]
Hi, thank you for fixing the issue I previously reported, https://github.com/SpriteLink/NIPAP/issues/1196. 
It seems that it is fixed in the latest version which is 0.29.7. The stable version still has the older vulnerabilities. Could you please include these updates in the stable version too?

**Comment by mariahaider** [comment]
Hi,

could someone please react on this issue?

Thansk!

**Comment by mariahaider** [comment]
Hi Lukas @garberg!

I am mentioning you here so that you can have a look at this issue.

Thanks in advance!

**Comment by garberg** [comment]
Hi, latest release pushed to the stable repo.

**Comment by mariahaider** [comment]
Thanks a lot!
