### ISSUE TITLE
Programmatically add prefix type host throws error 'Prefix of type host must have a parent (covering) prefix of type assignment'

### ISSUE THREAD

**Issue by ssnui** [SpriteLink/NIPAP#1214]
Hi,
I tried to add a prefix with type host into a parent prefix but always get this error:
   'Prefix of type host must have a parent (covering) prefix of type assignment'

I also tried using the CLI and got the same result.
```
# nipap address list 10.29.0.0/17
Searching for prefixes in any VRF...
VRF RT   Prefix                             #   Node  Order ID  Customer ID  Description
========================================================================================
65254:1  10.29.0.0/17                    R  -   None  None      None         Replication Failover Live Network (Routable)
65254:1    10.29.6.0/25                  A  -   None  None      None         Cloud REPL Live East

# nipap address add prefix 10.29.6.0/32 type host
Could not add prefix to NIPAP: Prefix of type host must have a parent (covering)                                                                                            prefix of type assignment
```
The parent prefix is 'Assignment' type, so why NIPAPcomplaints

But if I use the GUI to 'Add prefix from prefix' it works fine.
Here is my code:
```
args = { 'from-prefix': ['10.29.6.0/25'], 'prefix_length': 32 }

prefix_attr = {
		'type': 'host',
		'description': 'Test add host'
}
var result = addPrefix(restHost, prefix_attr, args);
if (result['id'] != 0)
	System.log('Add host successfully, id: ' + result['id']');
```

Can you tell me what data did I miss?
Thanks

**Comment by garberg** [comment]
You're missing the VRF when adding the prefix. Unless you've configured otherwise in your ~/.nipaprc, the default VRF which NIPAP will try to add the prefix to is "none" and from what I can see the parent assignment is in 65254:1.

**Comment by ssnui** [comment]
Thank you, after I added the vrf info into the prefix_attr, the call succeed. The vrf info was not mention in the API (Python, or XMLRPC), I was looking left and right in the sample test code but did not see it.
