### ISSUE TITLE
2 questions: Support for Oracle instead of Postgres / Multi-pool concurrency

### ISSUE THREAD

**Issue by lellinghaus** [SpriteLink/NIPAP#1228]
I have 2 questions. I am looking at NIPAP and wanted to find out if this is possible:
1) We use Oracle RDBMS exclusively can cannot bring a Postgres instance up. This is due to security issues in our environment. Can NIPAP be made to run with Oracle 12c instead of Postgres?
2) We have multiple environments and use an IP scheme that is consistent across all three environments, e.g. An IP address is allocated across multiple environments at once with the only difference being the 2nd octet. Can this be done in NIPAP?

Thank you.

**Comment by garberg** [comment]
1. Short answer: no. 
NIPAP is very closely tied to PostgreSQL as it uses postgres-specific data types and operators for storing and querying IP addresses. I don't know what's available today, but when we started developing NIPAP there was no similar support available in Oracle. Thus, porting NIPAP to Oracle would be a big undertaking.

2. Not really. It would need to be done in three separate requests and as long as all requests and releases of addresses are made in sync you would get the behavior you expect. In the long run probably doomed to fail... But if there is a static offset in the second offset, wouldn't it be enough to just allocate prefixes in one of the adress blocks and calculate the other two on-the-fly when needed?

**Comment by steffenschumacher** [comment]
1. I think if you run this in docker on a single linux host which only exposes https, then no one will be able to access your Postgres instance, and thus security concerns are largely gone? You could even set it up, so that Postgres is only available for the nipapd container, so even when you are on the linux host, you can't connect to it.
