### ISSUE TITLE
Error 500 in the WEB UI 

### ISSUE THREAD

**Issue by rphanikrishna** [SpriteLink/NIPAP#1246]
Hi, 

Am getting error 500 in the webui PFA the error log 

[mpm_event:notice] [pid 8303:tid 140218779935872] AH00489: Apache/2.4.38 (D$
[core:notice] [pid 8303:tid 140218779935872] AH00094: Command line: '/usr/s$
[mpm_event:notice] [pid 8303:tid 140218779935872] AH00491: caught SIGTERM, $
[mpm_event:notice] [pid 8386:tid 139793181373568] AH00489: Apache/2.4.38 (D$
[core:notice] [pid 8386:tid 139793181373568] AH00094: Command line: '/usr/s$
[mpm_event:notice] [pid 8386:tid 139793181373568] AH00491: caught SIGTERM, $
[mpm_event:notice] [pid 8508:tid 139729582179456] AH00489: Apache/2.4.38 (D$
[core:notice] [pid 8508:tid 139729582179456] AH00094: Command line: '/usr/s$

let me know if i have to make any changes

**Comment by el-es** [comment]
Mine is showing this after host reboot, but goes away when I restart nipapd through cli ([use sudo if needed] service nipapd restart)

**Comment by rphanikrishna** [comment]
Will check thank you
