### ISSUE TITLE
Instalation issues

### ISSUE THREAD

**Issue by Clavius-Walker** [SpriteLink/NIPAP#1256]
Trying to follow the guide found here;

https://spritelink.github.io/NIPAP/docs/install-debian.html

Installing on an Ubuntu 20.04 system and receiving the following dependency errors;

root@poller# apt install nipapd nipap-cli nipap-www python-pynipap
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nipap-www : Depends: python-pylons (>= 1.0) but it is not installable
             Depends: nipap-common but it is not going to be installed
             Depends: python-webob (>= 1.2) but it is not installable
 nipapd : Depends: nipap-common but it is not going to be installed
          Depends: python-psycopg2 but it is not installable
          Depends: python-flask but it is not installable
          Depends: python-flask-xml-rpc but it is not going to be installed
          Depends: python-flask-compress but it is not going to be installed
          Depends: python-tornado but it is not installable
          Depends: python-parsedatetime but it is not installable
E: Unable to correct problems, you have held broken packages.
root@poller:/home/mshelton# ^C
root@poller:/home/mshelton# uname -a
Linux poller 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@poller:/home/mshelton# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
root@poller#

################################

Should I be using a different repository?

**Comment by steffenschumacher** [comment]
I'd seriously consider using docker instead it also means you won't need to rely on package compatibility issues..
I'm doing a fork with python 3.6 support, but I don't know if I'll be able to figure out how to build updated packages for classic install, but I will be uploading new docker images if you're interested..

**Comment by bmullan** [comment]
I've got the same problem as @Clavius-Walker.

Unfortunately I don't use Docker so I guess I'll have to look for a different tool.

**Comment by steffenschumacher** [comment]
Yeah - i am working on porting everything to py36, but the web framework requires complete replacement, so it’ll be at least 1-2 months with the current number of hours I can afford to put into it..
Having said that - you should really try docker out - there’s good reasons why it popular..

Steffen Schumacher
+45 30662747

**Comment by andrnils** [comment]
I'm also running in to this issue. I see nothing about docker on your installation howto. Where shall I look?
I guess the other alternative is if you have deb-src repo, so that I could change dependencies to the correct ones.

**Comment by kalleswe** [comment]
Same on debian 11. Please fix and don't have outdated packages in your apt repo.

 nipapd : Depends: nipap-common but it is not going to be installed
          Depends: python-psycopg2 but it is not installable
          Depends: python-flask but it is not installable
          Depends: python-flask-xml-rpc but it is not going to be installed
          Depends: python-flask-restful but it is not installable
          Depends: python-flask-compress but it is not going to be installed
          Depends: python-tornado but it is not installable
          Depends: python-parsedatetime but it is not installable
          Depends: python-tz but it is not installable
          Depends: python-dateutil but it is not installable
          Depends: python-psutil but it is not installable
          Depends: python-pyparsing but it is not installable
          Depends: python-jwt but it is not installable
          Depends: python-requests but it is not installable

**Comment by garberg** [comment]
The main blocker for this has been the Python 3 upgrade. Now that it's merged I expect to build new packages during the coming week or so, which will be installable on a more modern system.

Current packages can be installed on Ubuntu 18.04 or Debian from the same era...

**Comment by garberg** [comment]
Okay, latest release 0.32.0 in the testing apt repo gets rid of the dependencies on Python 2.7. Successfully installed on the releases I had ready at hand: Ubuntu 18.04, Ubuntu 20.04 and Debian 11.

**Comment by garberg** [comment]
Closing.

**Comment by BeastyBlacksmith** [comment]
If I run the stuff from the documentation for Ubuntu 20.04 I still get that error
