### ISSUE TITLE
last_modified timestamp different in 0.29

### ISSUE THREAD

**Issue by webminster** [SpriteLink/NIPAP#1288]
I've upgraded from 0.29.8 to 0.29.9, and my code that prints out the last_modified timestamp on an entry appears to have changed.

Has there been some code change to last_modified?  With my previous code, the last_modified column printed:
04/16/18 19:53:41

The new pynipap module is returning:
04/07/21 19:16:44

And that's today.  It definitely wasn't modified today.

How can I debug this?  It's throwing off all my reporting.
-Alan

**Comment by garberg** [comment]
That's strange. Glancing through the diff between 0.29.8 and 0.29.9 I don't see any obvious candidates.

Does the timestamp match when the upgrade was made? Does it change? It'd be great if you could query the database directly and verify whether the timestamp in the database is correct or not?

**Comment by webminster** [comment]
Sorry it's taken so long to get back.  I think that it's UE on my part and can be ignored.
