### ISSUE TITLE
Missing bash_complete file in nipap-cli

### ISSUE THREAD

**Issue by webminster** [SpriteLink/NIPAP#1290]
The file /usr/share/doc/nipap-cli/bash_complete is missing from the nipap-cli 0.29.9-1 package.  Causes install error:

$ sudo apt-get install nipap-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  python3-ipy
The following NEW packages will be installed:
  nipap-cli python3-ipy
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 74.3 kB of archives.
After this operation, 343 kB of additional disk space will be used.
Do you want to continue? [Y/n] y\
Get:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-ipy all 1:0.83-1 [25.7 kB]
Get:2 http://spritelink.github.io/NIPAP/repos/apt stable/main amd64 nipap-cli all 0.29.9-1 [48.6 kB]
Fetched 74.3 kB in 0s (342 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package python3-ipy.
(Reading database ... 51393 files and directories currently installed.)
Preparing to unpack .../python3-ipy_1%3a0.83-1_all.deb ...
Unpacking python3-ipy (1:0.83-1) ...
Selecting previously unselected package nipap-cli.
Preparing to unpack .../nipap-cli_0.29.9-1_all.deb ...
Unpacking nipap-cli (0.29.9-1) ...
Setting up python3-ipy (1:0.83-1) ...
Setting up nipap-cli (0.29.9-1) ...
cp: cannot stat '/usr/share/doc/nipap-cli/bash_complete': No such file or directory
dpkg: error processing package nipap-cli (--configure):
 installed nipap-cli package post-installation script subprocess returned error exit status 1
E: Sub-process /usr/bin/dpkg returned an error code (1)

Note that the file is not where expected:
$ ls /usr/share/doc/nipap-cli
changelog.Debian.gz  copyright

**Comment by garberg** [comment]
Might be fixed in #1280, seems to work now at least :)
