### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by kevintdiep** [SpriteLink/NIPAP#1311]
I am attempting to install NIPAP on Debian 11.

The packages I am trying to install is the following.

sudo apt install nipapd nipap-cli nipap-www python-pynipap

Once the above parameter is executed.  These are packages that are not located.

E: Unable to locate package nipapd
E: Unable to locate package nipap-cli
E: Unable to locate package nipap-www
E: Unable to locate package python-pynipap

Any assistance would be grateful.

Thank you, Kevin

**Comment by cpjones44** [comment]
Yep, I too am having issues installing on Deb 11

`root@ipam:~# apt update
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Hit:4 http://spritelink.github.io/NIPAP/repos/apt stable InRelease
Hit:5 http://apt.postgresql.org/pub/repos/apt bullseye-pgdg InRelease
Fetched 44.1 kB in 1s (29.6 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
root@ipam:~# apt install nipapd
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nipapd : Depends: nipap-common but it is not going to be installed
          Depends: python-psycopg2 but it is not installable
          Depends: python-flask but it is not installable
          Depends: python-flask-xml-rpc but it is not going to be installed
          Depends: python-flask-compress but it is not going to be installed
          Depends: python-tornado but it is not installable
          Depends: python-parsedatetime but it is not installable
          Depends: python-tz but it is not installable
          Depends: python-dateutil but it is not installable
          Depends: python-psutil but it is not installable
          Depends: python-pyparsing but it is not installable
E: Unable to correct problems, you have held broken packages.
root@ipam:~#`

**Comment by garberg** [comment]
Should work now with latest release in testing repo, closing.
