### ISSUE TITLE
NIPAP spritelink.github.io repository does not work - 404 file not found

### ISSUE THREAD

**Issue by fanhanes** [SpriteLink/NIPAP#1382]
Hi, 

I am trying to install new fresh NIPAP server with help of this guide 
https://spritelink.github.io/NIPAP/docs/install-debian.html#getting

It looks like that repo directory is not available right now. When i try to open this URL  http://spritelink.github.io/NIPAP/repos/apt 
so I am getting 404 file not found error. Was this moved somewhere else? 

Thanks for help.

**Comment by fanhanes** [comment]
You are actually right i cannot browse that, sorry for confusion. Anyway, reason why I started to look around if resources are available is i have got these errors when I tried to install


ipam@ipam:~$ sudo apt install nipapd nipap-cli nipap-www python-pynipap
[sudo] password for ipam: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  javascript-common libjs-jquery libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib nipap-common python2 python2-minimal python2.7 python2.7-minimal python3-aniso8601 python3-dateutil
  python3-flask python3-flask-compress python3-flask-restful python3-flask-xml-rpc-re python3-icu python3-ipy python3-itsdangerous python3-parsedatetime python3-psutil python3-psycopg2
  python3-pyinotify python3-pynipap python3-simplejson python3-tornado python3-werkzeug
Suggested packages:
  apache2 | lighttpd | httpd python3-ldap python2-doc python-tk python2.7-doc binfmt-support python3-asgiref python3-dotenv python-flask-doc python-psutil-doc python-psycopg2-doc
  python-pyinotify-doc python3-pycurl python-tornado-doc ipython3 python-werkzeug-doc python3-lxml python3-watchdog
The following NEW packages will be installed:
  javascript-common libjs-jquery libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib nipap-cli nipap-common nipap-www nipapd python-pynipap python2 python2-minimal python2.7 python2.7-minimal
  python3-aniso8601 python3-dateutil python3-flask python3-flask-compress python3-flask-restful python3-flask-xml-rpc-re python3-icu python3-ipy python3-itsdangerous python3-parsedatetime
  python3-psutil python3-psycopg2 python3-pyinotify python3-pynipap python3-simplejson python3-tornado python3-werkzeug
0 upgraded, 31 newly installed, 0 to remove and 91 not upgraded.
Need to get 4,623 kB/6,639 kB of archives.
After this operation, 28.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://de.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libpython2.7-minimal amd64 2.7.18-13ubuntu1.2 [347 kB]
Err:2 http://spritelink.github.io/NIPAP/repos/apt stable/main amd64 python3-pynipap all 0.32.1-1
  403  Forbidden [IP: 185.199.108.153 80]
Get:3 http://de.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 python2.7-minimal amd64 2.7.18-13ubuntu1.2 [1,397 kB]
Get:4 http://de.archive.ubuntu.com/ubuntu jammy/universe amd64 python2-minimal amd64 2.7.18-3 [20.8 kB]
Get:5 http://de.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libpython2.7-stdlib amd64 2.7.18-13ubuntu1.2 [1,977 kB]
Get:6 http://de.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 python2.7 amd64 2.7.18-13ubuntu1.2 [250 kB]
Get:7 http://de.archive.ubuntu.com/ubuntu jammy/universe amd64 libpython2-stdlib amd64 2.7.18-3 [7,432 B]
Get:8 http://de.archive.ubuntu.com/ubuntu jammy/universe amd64 python2 amd64 2.7.18-3 [9,098 B]
Err:9 http://spritelink.github.io/NIPAP/repos/apt stable/main amd64 nipap-cli all 0.32.1-1
  403  Forbidden [IP: 185.199.108.153 80]
Err:10 http://spritelink.github.io/NIPAP/repos/apt stable/main amd64 nipap-common all 0.32.1-1
  403  Forbidden [IP: 185.199.108.153 80]
Err:11 http://spritelink.github.io/NIPAP/repos/apt stable/main amd64 nipap-www all 0.32.1-1
  403  Forbidden [IP: 185.199.108.153 80]
Err:12 http://spritelink.github.io/NIPAP/repos/apt stable/extra amd64 python3-flask-xml-rpc-re all 0.1.4-1
  403  Forbidden [IP: 185.199.108.153 80]
Err:13 http://spritelink.github.io/NIPAP/repos/apt stable/main amd64 nipapd all 0.32.1-1
  403  Forbidden [IP: 185.199.108.153 80]
Err:14 http://spritelink.github.io/NIPAP/repos/apt stable/main amd64 python-pynipap all 0.32.1-1
  403  Forbidden [IP: 185.199.108.153 80]
Fetched 4,007 kB in 1s (2,924 kB/s)
E: Failed to fetch http://spritelink.github.io/NIPAP/repos/apt/pool/main/p/pynipap/python3-pynipap_0.32.1-1_all.deb  403  Forbidden [IP: 185.199.108.153 80]
E: Failed to fetch http://spritelink.github.io/NIPAP/repos/apt/pool/main/n/nipap-cli/nipap-cli_0.32.1-1_all.deb  403  Forbidden [IP: 185.199.108.153 80]
E: Failed to fetch http://spritelink.github.io/NIPAP/repos/apt/pool/main/n/nipap/nipap-common_0.32.1-1_all.deb  403  Forbidden [IP: 185.199.108.153 80]
E: Failed to fetch http://spritelink.github.io/NIPAP/repos/apt/pool/main/n/nipap-www/nipap-www_0.32.1-1_all.deb  403  Forbidden [IP: 185.199.108.153 80]
E: Failed to fetch http://spritelink.github.io/NIPAP/repos/apt/pool/extra/f/flask-xml-rpc-re/python3-flask-xml-rpc-re_0.1.4-1_all.deb  403  Forbidden [IP: 185.199.108.153 80]
E: Failed to fetch http://spritelink.github.io/NIPAP/repos/apt/pool/main/n/nipap/nipapd_0.32.1-1_all.deb  403  Forbidden [IP: 185.199.108.153 80]
E: Failed to fetch http://spritelink.github.io/NIPAP/repos/apt/pool/main/p/pynipap/python-pynipap_0.32.1-1_all.deb  403  Forbidden [IP: 185.199.108.153 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by garberg** [comment]
That's really strange, I can fetch the files from the URLs in the error message. Can you try fetching one with wget/curl/whatever?

**Comment by fanhanes** [comment]
Alright I figured it out. It was firewall who was intercepting into communication. Issue solved. Case can be closed or even deleted.

**Comment by garberg** [comment]
Okay, thanks for letting us know, closing this issue.
