### ISSUE TITLE
Enable jnipap unit tests in Travis-CI configuration

### ISSUE THREAD

**Issue by garberg** [SpriteLink/NIPAP#337]
Make sure Travis-CI runs the jnipap unit tests.

**Comment by bbaja42** [comment]
Hi, I think that Travis-CI is already running the unit tests, so this issue can be resolved?

**Comment by plajjan** [comment]
You're correct!
This is fixed through https://github.com/SpriteLink/NIPAP/commit/e430f71a2929477eea73f290ada68333bfb1e226
