### ISSUE TITLE
Portability fix

### ISSUE THREAD

**Issue by darkfiberiru** [SpriteLink/NIPAP#645]
There seem to be a lot of simple code portability that could be cleaned up so that the project works cleanly on more nix variants. Both a swap from */usr/bin/python* to */usr/bin/env python* and adding up setup.cfg files with prefix defaults instead of hard coding file install locations. My personal goal is to make the install go cleaner on freebsd but any work would be targeted at all nix variants.

Thoughts? I just wanted to get opinions before I put in pull requests.

**Comment by plajjan** [comment]
Seeing how this does not directly track an issue but is more of a question, and one without much recent activity, I will close this. Feel free to reopen it, or open a new one, if you would like to ask more questions. Naturally, PRs are more than welcome as well :)
