### ISSUE TITLE
cli: Tracebacks from executing "nipap pool view <pool>"

### ISSUE THREAD

**Issue by tedpelas** [SpriteLink/NIPAP#672]
$ nipap pool view link-pni-x-x
-- Pool
  ID                         : 10
  Name                       : link-pni-x-x
  Description                : Link networks
  Default type               : assignment
  Implied VRF RT / name      : 65000:30 / xxx
  Preflen (v4/v6)            : 31 / 112
-- Extra Attributes
-- Tags
-- Statistics
Traceback (most recent call last):
  File "/usr/bin/nipap", line 122, in <module>
    cmd.exe(cmd.arg, cmd.exe_options, options)
  File "/usr/lib/python2.7/dist-packages/nipap_cli/nipap_cli.py", line 798, in view_pool
    used_percent_v6 = (float(p.used_prefixes_v6)/p.total_prefixes_v6)*100
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'

**Comment by plajjan** [comment]
The function that calculates the number of free prefixes returns NULL for various error conditions which leads to these values being None in the CLI and therefore ending up with a Traceback.

In the web UI we explicitly check things like number of member prefixes in pool and that the default prefix length is set to a value. Those are the basic prerequisites for this thing to work and so we simply avoid trying to print any statistics under those conditions. Doing the same in the CLI would make sense from that perspective.

But I'm more interested in the underlying issue. Should free_prefixes_v6 be 0 or None when there are no prefixes in pool or the default prefix length hasn't been set?
free_addresses_v6 is 0 under those same conditions where free_prefixes_v6 would be None/NULL, so there is certainly an inconsistency there.

Why None and not 0? Well, it might be nice to differentiate a pool that is full (free_prefixes_vX = 0) from one that doesn't have any IPvX member prefixes at all. A full pool should lead to it being filled up with more member prefixes so it becomes non-full whereas a pool that doesn't have any member prefixes of a certain address family might be per design.

@garberg waddya think?

**Comment by plajjan** [comment]
Related to #693.
