### ISSUE TITLE
VRF field not populated

### ISSUE THREAD

**Issue by garberg** [SpriteLink/NIPAP#673]
Sometimes when entering the AngularJS-based add prefix page to add prefixes from a pool or other prefix, the VRF field is not populated. Annoying with intermittent faults, I have no screenshot/JavaScript error to display currently, but adding this to keep track of the issue.

**Comment by plajjan** [comment]
Let's try upgrading to the latest version of AngularJS and see if that solves it...

**Comment by plajjan** [comment]
How often does this happen when you reproduce it? I've tried a few times now and haven't bumped into it thus far.

Will the VRF display correctly in the VRF selection box and then be added to the wrong VRF or will the VRF selection box also show the wrong thing?

**Comment by plajjan** [comment]
Ok, I can reproduce it too. Just clicked the "add prefix from prefix" a bunch of times to open in a new tab and a few of the windows (something like one in ten) doesn't have the VRF selector set to the correct VRF.
