### ISSUE TITLE
Upgrade AngularJS to 1.3.8

### ISSUE THREAD

**Issue by plajjan** [SpriteLink/NIPAP#680]
We are currently using AngularJS 1.2 and there are a number of new features and fixes in AngularJS 1.3 that we probably want.

From the release notes of 1.3:
```Angular 1.3 provides a boost in performance versus the previous versions. The Angular development team concentrated on making it less overhead. According to Jeff Cross and Brian Ford at the Ng-Europe conference, they achieved 4.3 times faster DOM manipulation with 73% less garbage and 3.5 times faster digest with 87% less garbage versus 1.2.0 version based on their largetable benchmark tests.```

... this sounds pretty nice. The performance (or lack thereof) is quite noticeable on the prefix list page.

Another sweet feature is the possibility of doing one-way bindings, thereby improving performance considerably for use cases where two-way bindings is not strictly necessary. Most of our listing pages, most notably the prefix list page, should be able to gain from this.

I'm not sure at all how we should test 1.3. Do we need to at all?

**Comment by plajjan** [comment]
Relevant: https://docs.angularjs.org/guide/migration#migrating-from-1-2-to-1-3

**Comment by plajjan** [comment]
Heh, it just hit me that the prefix list page isn't implemented using AngularJS so the performance gain there would be none from this upgrade :P

**Comment by garberg** [comment]
I gave this a quick shot and noticed that upgrading to AngularJS 1.3 breaks setting focus on the text input field in the pool and VRF selector popups. As they disappear when clicked (even if clicked in the text field) this essentially breaks these widgets.

I'll look into this again after I've fixed the selector widgets.
