### ISSUE TITLE
Add CLI argument to specify output columns

### ISSUE THREAD

**Issue by plajjan** [SpriteLink/NIPAP#684]
While the CLI isn't meant for scripting (you should use Pynipap!!) there are cases when it is fairly handy to do a bit of simple scripting using bash, awk and friends. To simplify this further, we should have an argument to the nipap CLI which can be used to specify the output columns to print.

Further, we should have an argument to suppress column headers and similar that makes it more difficult to parse out the correct columns.

**Comment by garberg** [comment]
It'd also be good to be able to configure what columns to display in .nipaprc.

**Comment by plajjan** [comment]
I would like to adopt the syntax used by LVM tools, for example lvs, where the user can add columns to the standard set of columns or make a completely custom column selection, like so:
```
root@lingloi320:~# lvs
  LV     VG         Attr      LSize   Pool Origin Data%  Move Log Copy%  Convert
  root   lingloi320 -wi-ao--- 145,83g                                           
  swap_1 lingloi320 -wi-ao---   2,98g                                           
root@lingloi320:~# lvs -o +devices
  LV     VG         Attr      LSize   Pool Origin Data%  Move Log Copy%  Convert Devices                      
  root   lingloi320 -wi-ao--- 145,83g                                            /dev/mapper/sda5_crypt(0)    
  swap_1 lingloi320 -wi-ao---   2,98g                                            /dev/mapper/sda5_crypt(37333)
root@lingloi320:~# lvs -o devices
  Devices                      
  /dev/mapper/sda5_crypt(0)    
  /dev/mapper/sda5_crypt(37333)
root@lingloi320:~# 
```
As can be seen, first we have a standard layout, then there's one with the "devices" column added to the standard layout and last we make our completely customer layout by just specifying the "devices" column.
