### ISSUE TITLE
Search hangs whole application on first try sometimes

### ISSUE THREAD

**Issue by jhildings** [SpriteLink/NIPAP#695]

**Comment by plajjan** [comment]
I've heard this from some other users too but without more information we can neither reproduce consistently (I don't think I've ever seen it) or fix it.

There are changes going into the web UI, especially with regards to our rewrite in AngularJS, which might fix this without us even knowing about it. Anyway, I'm closing this for now. Feel free to reopen if we have any more specific leads.
