### ISSUE TITLE
Fix LDAP the way Symmetria wants it

### ISSUE THREAD

**Issue by plajjan** [SpriteLink/NIPAP#706]
Details to be figured out at some point...

**Comment by toreanderson** [comment]
I'm not sure if this is «the say Symmetria wants it», but I too have found the current LDAP auth implementation difficult to use in my company. The main difficulty stems from the fact that we structure our user objects into different RDNs depending on their location/department. Consider for example:

* uid=bob,ou=Operations,dc=acme,dc=com
* uid=alice,ou=Engineering,dc=acme,dc=com

It is (as far as I can tell) impossible to use NIPAP's current LDAP auth implementation to allow both «bob» and «alice» to log in (while using a single auth backend). The main problem is that the `binddn_fmt` setting assumes that all user objects are located immediately below a common RDN. So I could do `binddn_fmt = uid={},ou=Operations,dc=acme,dc=com` which would allow «bob» and his ops colleagues to log in, but obviously this would lock out «alice» and any other engineers.

The way LDAP authentication is usually implemented something like this:

1. A search with a user-configured filter (for example: `(&(uid=alice)(objectClass=NIPAPUser))` performed below a configured search base DN (`dc=acme,dc=com`). The user can usually configure the scope of the search also (the default is usually subtree). The bind is done anonymously, or possibly with statically configured credentials if this is required for read-only access to the directory.
   * If the search doesn't find any objects, the authentication fails.
2. Attempt to bind to the LDAP server using the DN found in step 1 (`uid=alice,ou=Engineering,dc=acme,dc=com`) plus the user-supplied password as credentials. If this succeeds, the user is successfully authenticated.

I might just try to patch this in myself at some point, but I'll need to refresh my rather rusty Python skills first.

**Comment by plajjan** [comment]
To clarify the rather vague description of this issue.. What Symmetria wanted (or still wants?) was to have authorization per group and be able to delegate resources (VRFs, prefixes) to a certain group. Ie, instead of having global read/write or read-only, you get read/write or read-only per resource.

This issue was created, somewhat as a joke, to have something on bountysource that Symmetria could put a bounty on.. but he never did.

**Comment by plajjan** [comment]
@toreanderson as for your comment. I think you are right, it's not possible today, and modifying the authentication part to support your schema would be a good addition, especially if we can do it without further increasing the complexity of the LDAP configuration. I'd be happy to review patches or give feedback, either here or on IRC.

I do think you should open a separate issue though :P

**Comment by plajjan** [comment]
I'm closing this issue to avoid confusion ;)
