### ISSUE TITLE
Upload pynipap to PyPI

### ISSUE THREAD

**Issue by jameydeorio** [SpriteLink/NIPAP#710]
As far as I can tell, there's no package for pynipap on PyPI. So adding it to a requirements file isn't possible, which is not ideal for automation.

**Comment by plajjan** [comment]
You are right, pynipap should be on pypi, which is why I've just uploaded it there! :)
Also updated release-document so we won't forget to update it in the future - see 43504ad28b27623137b7d806e81731b4315b01f2
