### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by drzero42** [SpriteLink/NIPAP#711]
When I try to tab-complete 'nipap address add node' I get this Traceback:

Traceback (most recent call last):
  File "/usr/bin/helper-nipap", line 50, in <module>
    comp = sorted(cmd.complete())
  File "/usr/lib/python2.7/dist-packages/nipap_cli/command.py", line 264, in complete
    comp += v['complete'](self.inp_cmd[-1])
  File "/usr/lib/python2.7/dist-packages/nipap_cli/nipap_cli.py", line 1747, in complete_node
    cmd = cfg.get('global', 'complete_node_cmd')
AttributeError: 'NoneType' object has no attribute 'get'

I am on Ubuntu 14.04.
$ nipap --version
nipap CLI client version: 0.27.4
pynipap version: 0.27.3
nipapd version: 0.27.3

**Comment by plajjan** [comment]
The traceback is generated by nipap-helper, which is the application that does tab completion for the nipap cli. It tries to read parameters from its configuration file but fails to do so as the configuration file is not available. It tries to access ~/.nipaprc so my guess is that you haven't defined a .nipaprc file.

Obviously we should handle this in a more graceful way. I'm not quite sure how though.
* Suppress error?
* Print error message? I think it's weird for a tab completion program to print an error message..

**Comment by plajjan** [comment]
I don't think writing an error message makes much sense. I've fiddled around with it a bit and I can't come up with a good way to print an error message.

Therefore, suppressing the error message is the only solution I see.
