### ISSUE TITLE
pynipap needs documentation love

### ISSUE THREAD

**Issue by jameydeorio** [SpriteLink/NIPAP#712]
The existing documentation on the pynipap tool is sparse, to say the least. And the comments in the source code aren't very explicit. As a random example, Prefix.find_free(self, vrf, args), as a developer using this for the first time, I want to know what args is supposed to be.

I'm forced to read the tests to see how to use things.

**Comment by garberg** [comment]
pynipap is designed to be thin, so most arguments are sent straight through pynipap to the backend. Thus, most information you need when using pynipap is actually in the documentation for the backend (http://nipap.readthedocs.org/en/v0.26.4/nipap/).

I understand that this can be confusing, at the very least this could be expressed more clearly in the pynipap documentation. We want to avoid documenting the same options & arguments for every client library though, so writing full documentation for pynipap is not really an option.

**Comment by jameydeorio** [comment]
That makes sense. Thanks for pointing me in that direction. I'd agree that pynipap should more explicitly state this, and perhaps link to those docs.
