### ISSUE TITLE
expire usage bug (invalid defaults)

### ISSUE THREAD

**Issue by CrackerJackMack** [SpriteLink/NIPAP#721]
when testing nipap for a massive import/conversion of our current IPAM I ran into the following issue using nipap-www.  When the expire field is missing it's default is `None` is is then represented as `str(self.expire)`.  This makes the default value in the webform invalid. [related commit](https://github.com/SpriteLink/NIPAP/pull/658/files#diff-26330bff8775394301a1bdaeef7e5d43R860)

In a related matter clearing the expires field sets the expire date to midnight.  It appears that setting the `expires = None` using pynipap doesn't quite have the desired results, which is always setting the expired attribute even when you don't want it to expire.

**Comment by plajjan** [comment]
Can't read code now because I'm on a phone, so this is from the top of my head.

In the database we represent the case of no expiration date as positive infinity, since postgres timestamps can handle that. Unfortunately this cannot be represented over XML-RPC so instead we have null to signify that.

I know this was a little bit tricky with pynipap so I'm not very surprised if there is a bug in there. I'll have a look to see if we can weed this out.

**Comment by toreanderson** [comment]
This causes the web interface to produce the following XML:

```
<methodCall>
<methodName>edit_prefix</methodName>
<params>
[...]
<member>
<name>attr</name>
<value><struct>
[...]
<member>
<name>expires</name>
<value><string>None</string></value>
</member>
[...]
```

This in turn appears to be interpreted by the backend as "right now", so by simply opening a prefix for editing and pressing "save" will cause the prefix to end up as having expired.

I think a simple fix would be to strip out the `expires` attribute if its value is equal to `None`. At least when I call `edit_prefix` directly from my scripts, and omit the `expires` attribute in the `attr` struct, the stored `expires` value stays the same (i.e., no expiration date).

**Comment by plajjan** [comment]
The issue is likely that None, as in NULL/nil, is expected while "None" is sent. In XML-RPC this is explicitly shown with the string tag in ```<value><string>None</string></value>```. I'll have a deeper look into this.
