### ISSUE TITLE
Unable to execute query: permission denied for relation 

### ISSUE THREAD

**Issue by florinciprian** [SpriteLink/NIPAP#724]
Hello,

I have installed NIPAP and I can't add prefixes, pools, vrf from web UI. I receive : 

Unable to execute query: permission denied for relation ip_net_plan
Unable to execute query: permission denied for relation ip_net_plan
Unable to execute query: permission denied for relation ip_net_vrf

tail -f /var/log/postgresql/postgresql-9.4-main.log
	            )
	            JOIN ip_net_vrf AS vrf ON (p1.vrf_id = vrf.id)
	            LEFT JOIN ip_net_pool AS pool ON (p1.pool_id = pool.id)
	            -- possible set where conditions, if we are doing a parent_prefix operation

	            ORDER BY vrf_rt_order(vrf.rt) NULLS FIRST, p1.prefix, CASE WHEN p1.prefix = p2.prefix THEN 0 ELSE 1 END OFFSET 0) AS a ORDER BY vrf_rt_order(vrf_rt) NULLS FIRST, prefix
2015-04-03 15:50:39 EEST [9212-3] nipap@nipap ERROR:  permission denied for relation ip_net_vrf
2015-04-03 15:50:39 EEST [9212-4] nipap@nipap STATEMENT:  SELECT * FROM ip_net_vrf ORDER BY vrf_rt_order(rt) NULLS FIRST
2015-04-03 15:50:39 EEST [9213-1] nipap@nipap ERROR:  permission denied for relation ip_net_vrf
2015-04-03 15:50:39 EEST [9213-2] nipap@nipap STATEMENT:  SELECT * FROM ip_net_vrf ORDER BY vrf_rt_order(rt) NULLS FIRST
2015-04-03 15:53:36 EEST [9213-3] nipap@nipap ERROR:  permission denied for relation ip_net_plan
2015-04-03 15:53:36 EEST [9213-4] nipap@nipap STATEMENT:
	    SELECT
	        id,
	        vrf_id,
	        vrf_rt,
	        vrf_name,
	        family,
	        display,
	        match,
	        prefix,
	        prefix_length,
	        display_prefix::text AS display_prefix,
	        description,
	        comment,
	        inherited_tags,
	        tags,
	        node,
	        pool_id,
	        pool_name,
	        type,
	        status,
	        indent,
	        country,
	        order_id,
	        customer_id,
	        external_key,
	        authoritative_source,
	        alarm_priority,
	        monitor,
	        vlan,
	        added,
	        last_modified,
	        children,
	        total_addresses,
	        used_addresses,
	        free_addresses,
	        avps,
	        expires
	    FROM (
	        SELECT DISTINCT ON(vrf_rt_order(vrf.rt), p1.prefix) p1.id,
	            p1.prefix,
	            p1.display_prefix,
	            p1.description,
	            p1.comment,
	            COALESCE(p1.inherited_tags, '{}') AS inherited_tags,
	            COALESCE(p1.tags, '{}') AS tags,
	            p1.node,
	            pool.id AS pool_id,
	            pool.name AS pool_name,
	            p1.type,
	            p1.indent,
	            p1.country,
	            p1.order_id,
	            p1.customer_id,
	            p1.external_key,
	            p1.authoritative_source,
	            p1.alarm_priority,
	            p1.monitor,
	            p1.vlan,
	            p1.added,
	            p1.last_modified,
	            p1.children,
	            p1.total_addresses,
	            p1.used_addresses,
	            p1.free_addresses,
	            p1.status,
	            p1.avps,
	            p1.expires,
	            vrf.id AS vrf_id,
	            vrf.rt AS vrf_rt,
	            vrf.name AS vrf_name,
	            masklen(p1.prefix) AS prefix_length,
	            family(p1.prefix) AS family,
	            ((p1.prefix << p2.display_prefix OR p2.prefix <<= p1.prefix ) OR (p2.prefix >>= p1.prefix AND p1.indent BETWEEN p2.indent AND p2.indent + 0)) AS display,
	            CASE WHEN p1.prefix = p2.prefix THEN true ELSE false END AS match
	            FROM ip_net_plan AS p1
	            -- possible set LEFT OUTER JOIN, if we are doing a parent_prefix operation
	             JOIN ip_net_plan AS p2 ON
	            (
	                (
	                    (p1.vrf_id = p2.vrf_id)
	                    AND
	                    (
	                        -- Join in the parents (p1) of matching prefixes (p2)
	                        (iprange(p1.prefix) >>= iprange(p2.prefix) )
	                        OR
	                        -- Join in the children (p1) of matching prefixes (p2)
	                        (iprange(p1.prefix) << iprange(p2.prefix) AND p1.indent BETWEEN p2.indent AND p2.indent + 0)
	                        OR
	                        -- Join in all neighbors (p1) of matching prefixes (p2)
	                        (true = true AND iprange(p1.prefix) << iprange(p2.display_prefix::cidr) AND p1.indent = p2.indent)
	                    )
	                )
	                -- set match conditions for p2
	                AND p2.id IN (
	                    SELECT inp.id FROM ip_net_plan AS inp JOIN ip_net_vrf AS vrf ON inp.vrf_id = vrf.id LEFT JOIN ip_net_pool AS pool ON inp.pool_id = pool.id
	                        WHERE  ( ( ( ( ( COALESCE(inp.comment, '') ~* ''  OR  COALESCE(inp.description, '') ~* '' )  OR  COALESCE(inp.node, '') ~* '' )  OR  COALESCE(inp.order_id, '') ~* '' )  OR  COALESCE(inp.customer_id, '') ~* '' )  AND  inp.indent = '0' )
	                    ORDER BY vrf_rt_order(vrf.rt) NULLS FIRST, prefix
	                    LIMIT 50
	                )
	            )
	            JOIN ip_net_vrf AS vrf ON (p1.vrf_id = vrf.id)
	            LEFT JOIN ip_net_pool AS pool ON (p1.pool_id = pool.id)
	            -- possible set where conditions, if we are doing a parent_prefix operation

	            ORDER BY vrf_rt_order(vrf.rt) NULLS FIRST, p1.prefix, CASE WHEN p1.prefix = p2.prefix THEN 0 ELSE 1 END OFFSET 0) AS a ORDER BY vrf_rt_order(vrf_rt) NULLS FIRST, prefix
2015-04-03 15:53:36 EEST [9267-1] nipap@nipap ERROR:  permission denied for relation ip_net_plan
2015-04-03 15:53:36 EEST [9267-2] nipap@nipap STATEMENT:
	    SELECT
	        id,
	        vrf_id,
	        vrf_rt,
	        vrf_name,
	        family,
	        display,
	        match,
	        prefix,
	        prefix_length,
	        display_prefix::text AS display_prefix,
	        description,
	        comment,
	        inherited_tags,
	        tags,
	        node,
	        pool_id,
	        pool_name,
	        type,
	        status,
	        indent,
	        country,
	        order_id,
	        customer_id,
	        external_key,
	        authoritative_source,
	        alarm_priority,
	        monitor,
	        vlan,
	        added,
	        last_modified,
	        children,
	        total_addresses,
	        used_addresses,
	        free_addresses,
	        avps,
	        expires
	    FROM (
	        SELECT DISTINCT ON(vrf_rt_order(vrf.rt), p1.prefix) p1.id,
	            p1.prefix,
	            p1.display_prefix,
	            p1.description,
	            p1.comment,
	            COALESCE(p1.inherited_tags, '{}') AS inherited_tags,
	            COALESCE(p1.tags, '{}') AS tags,
	            p1.node,
	            pool.id AS pool_id,
	            pool.name AS pool_name,
	            p1.type,
	            p1.indent,
	            p1.country,
	            p1.order_id,
	            p1.customer_id,
	            p1.external_key,
	            p1.authoritative_source,
	            p1.alarm_priority,
	            p1.monitor,
	            p1.vlan,
	            p1.added,
	            p1.last_modified,
	            p1.children,
	            p1.total_addresses,
	            p1.used_addresses,
	            p1.free_addresses,
	            p1.status,
	            p1.avps,
	            p1.expires,
	            vrf.id AS vrf_id,
	            vrf.rt AS vrf_rt,
	            vrf.name AS vrf_name,
	            masklen(p1.prefix) AS prefix_length,
	            family(p1.prefix) AS family,
	            ((p1.prefix << p2.display_prefix OR p2.prefix <<= p1.prefix ) OR (p2.prefix >>= p1.prefix AND p1.indent BETWEEN p2.indent AND p2.indent + 0)) AS display,
	            CASE WHEN p1.prefix = p2.prefix THEN true ELSE false END AS match
	            FROM ip_net_plan AS p1
	            -- possible set LEFT OUTER JOIN, if we are doing a parent_prefix operation
	             JOIN ip_net_plan AS p2 ON
	            (
	                (
	                    (p1.vrf_id = p2.vrf_id)
	                    AND
	                    (
	                        -- Join in the parents (p1) of matching prefixes (p2)
	                        (iprange(p1.prefix) >>= iprange(p2.prefix) )
	                        OR
	                        -- Join in the children (p1) of matching prefixes (p2)
	                        (iprange(p1.prefix) << iprange(p2.prefix) AND p1.indent BETWEEN p2.indent AND p2.indent + 0)
	                        OR
	                        -- Join in all neighbors (p1) of matching prefixes (p2)
	                        (true = true AND iprange(p1.prefix) << iprange(p2.display_prefix::cidr) AND p1.indent = p2.indent)
	                    )
	                )
	                -- set match conditions for p2
	                AND p2.id IN (
	                    SELECT inp.id FROM ip_net_plan AS inp JOIN ip_net_vrf AS vrf ON inp.vrf_id = vrf.id LEFT JOIN ip_net_pool AS pool ON inp.pool_id = pool.id
	                        WHERE  ( ( ( ( ( COALESCE(inp.comment, '') ~* ''  OR  COALESCE(inp.description, '') ~* '' )  OR  COALESCE(inp.node, '') ~* '' )  OR  COALESCE(inp.order_id, '') ~* '' )  OR  COALESCE(inp.customer_id, '') ~* '' )  AND  inp.indent = '0' )
	                    ORDER BY vrf_rt_order(vrf.rt) NULLS FIRST, prefix
	                    LIMIT 50
	                )
	            )
	            JOIN ip_net_vrf AS vrf ON (p1.vrf_id = vrf.id)
	            LEFT JOIN ip_net_pool AS pool ON (p1.pool_id = pool.id)
	            -- possible set where conditions, if we are doing a parent_prefix operation

	            ORDER BY vrf_rt_order(vrf.rt) NULLS FIRST, p1.prefix, CASE WHEN p1.prefix = p2.prefix THEN 0 ELSE 1 END OFFSET 0) AS a ORDER BY vrf_rt_order(vrf_rt) NULLS FIRST, prefix
2015-04-03 15:53:36 EEST [9267-3] nipap@nipap ERROR:  permission denied for relation ip_net_plan
2015-04-03 15:53:36 EEST [9267-4] nipap@nipap STATEMENT:
	    SELECT
	        id,
	        vrf_id,
	        vrf_rt,
	        vrf_name,
	        family,
	        display,
	        match,
	        prefix,
	        prefix_length,
	        display_prefix::text AS display_prefix,
	        description,
	        comment,
	        inherited_tags,
	        tags,
	        node,
	        pool_id,
	        pool_name,
	        type,
	        status,
	        indent,
	        country,
	        order_id,
	        customer_id,
	        external_key,
	        authoritative_source,
	        alarm_priority,
	        monitor,
	        vlan,
	        added,
	        last_modified,
	        children,
	        total_addresses,
	        used_addresses,
	        free_addresses,
	        avps,
	        expires
	    FROM (
	        SELECT DISTINCT ON(vrf_rt_order(vrf.rt), p1.prefix) p1.id,
	            p1.prefix,
	            p1.display_prefix,
	            p1.description,
	            p1.comment,
	            COALESCE(p1.inherited_tags, '{}') AS inherited_tags,
	            COALESCE(p1.tags, '{}') AS tags,
	            p1.node,
	            pool.id AS pool_id,
	            pool.name AS pool_name,
	            p1.type,
	            p1.indent,
	            p1.country,
	            p1.order_id,
	            p1.customer_id,
	            p1.external_key,
	            p1.authoritative_source,
	            p1.alarm_priority,
	            p1.monitor,
	            p1.vlan,
	            p1.added,
	            p1.last_modified,
	            p1.children,
	            p1.total_addresses,
	            p1.used_addresses,
	            p1.free_addresses,
	            p1.status,
	            p1.avps,
	            p1.expires,
	            vrf.id AS vrf_id,
	            vrf.rt AS vrf_rt,
	            vrf.name AS vrf_name,
	            masklen(p1.prefix) AS prefix_length,
	            family(p1.prefix) AS family,
	            ((p1.prefix << p2.display_prefix OR p2.prefix <<= p1.prefix ) OR (p2.prefix >>= p1.prefix AND p1.indent BETWEEN p2.indent AND p2.indent + 0)) AS display,
	            CASE WHEN p1.prefix = p2.prefix THEN true ELSE false END AS match
	            FROM ip_net_plan AS p1
	            -- possible set LEFT OUTER JOIN, if we are doing a parent_prefix operation
	             JOIN ip_net_plan AS p2 ON
	            (
	                (
	                    (p1.vrf_id = p2.vrf_id)
	                    AND
	                    (
	                        -- Join in the parents (p1) of matching prefixes (p2)
	                        (iprange(p1.prefix) >>= iprange(p2.prefix) )
	                        OR
	                        -- Join in the children (p1) of matching prefixes (p2)
	                        (iprange(p1.prefix) << iprange(p2.prefix) AND p1.indent BETWEEN p2.indent AND p2.indent + 0)
	                        OR
	                        -- Join in all neighbors (p1) of matching prefixes (p2)
	                        (true = true AND iprange(p1.prefix) << iprange(p2.display_prefix::cidr) AND p1.indent = p2.indent)
	                    )
	                )
	                -- set match conditions for p2
	                AND p2.id IN (
	                    SELECT inp.id FROM ip_net_plan AS inp JOIN ip_net_vrf AS vrf ON inp.vrf_id = vrf.id LEFT JOIN ip_net_pool AS pool ON inp.pool_id = pool.id
	                        WHERE  ( ( ( ( ( COALESCE(inp.comment, '') ~* ''  OR  COALESCE(inp.description, '') ~* '' )  OR  COALESCE(inp.node, '') ~* '' )  OR  COALESCE(inp.order_id, '') ~* '' )  OR  COALESCE(inp.customer_id, '') ~* '' )  AND  inp.indent = '0' )
	                    ORDER BY vrf_rt_order(vrf.rt) NULLS FIRST, prefix
	                    LIMIT 50
	                )
	            )
	            JOIN ip_net_vrf AS vrf ON (p1.vrf_id = vrf.id)
	            LEFT JOIN ip_net_pool AS pool ON (p1.pool_id = pool.id)
	            -- possible set where conditions, if we are doing a parent_prefix operation

	            ORDER BY vrf_rt_order(vrf.rt) NULLS FIRST, p1.prefix, CASE WHEN p1.prefix = p2.prefix THEN 0 ELSE 1 END OFFSET 0) AS a ORDER BY vrf_rt_order(vrf_rt) NULLS FIRST, prefix
2015-04-03 15:53:36 EEST [9268-1] nipap@nipap ERROR:  permission denied for relation ip_net_plan
2015-04-03 15:53:36 EEST [9268-2] nipap@nipap STATEMENT:
	    SELECT
	        id,
	        vrf_id,
	        vrf_rt,
	        vrf_name,
	        family,
	        display,
	        match,
	        prefix,
	        prefix_length,
	        display_prefix::text AS display_prefix,
	        description,
	        comment,
	        inherited_tags,
	        tags,
	        node,
	        pool_id,
	        pool_name,
	        type,
	        status,
	        indent,
	        country,
	        order_id,
	        customer_id,
	        external_key,
	        authoritative_source,
	        alarm_priority,
	        monitor,
	        vlan,
	        added,
	        last_modified,
	        children,
	        total_addresses,
	        used_addresses,
	        free_addresses,
	        avps,
	        expires
	    FROM (
	        SELECT DISTINCT ON(vrf_rt_order(vrf.rt), p1.prefix) p1.id,
	            p1.prefix,
	            p1.display_prefix,
	            p1.description,
	            p1.comment,
	            COALESCE(p1.inherited_tags, '{}') AS inherited_tags,
	            COALESCE(p1.tags, '{}') AS tags,
	            p1.node,
	            pool.id AS pool_id,
	            pool.name AS pool_name,
	            p1.type,
	            p1.indent,
	            p1.country,
	            p1.order_id,
	            p1.customer_id,
	            p1.external_key,
	            p1.authoritative_source,
	            p1.alarm_priority,
	            p1.monitor,
	            p1.vlan,
	            p1.added,
	            p1.last_modified,
	            p1.children,
	            p1.total_addresses,
	            p1.used_addresses,
	            p1.free_addresses,
	            p1.status,
	            p1.avps,
	            p1.expires,
	            vrf.id AS vrf_id,
	            vrf.rt AS vrf_rt,
	            vrf.name AS vrf_name,
	            masklen(p1.prefix) AS prefix_length,
	            family(p1.prefix) AS family,
	            ((p1.prefix << p2.display_prefix OR p2.prefix <<= p1.prefix ) OR (p2.prefix >>= p1.prefix AND p1.indent BETWEEN p2.indent AND p2.indent + 0)) AS display,
	            CASE WHEN p1.prefix = p2.prefix THEN true ELSE false END AS match
	            FROM ip_net_plan AS p1
	            -- possible set LEFT OUTER JOIN, if we are doing a parent_prefix operation
	             JOIN ip_net_plan AS p2 ON
	            (
	                (
	                    (p1.vrf_id = p2.vrf_id)
	                    AND
	                    (
	                        -- Join in the parents (p1) of matching prefixes (p2)
	                        (iprange(p1.prefix) >>= iprange(p2.prefix) )
	                        OR
	                        -- Join in the children (p1) of matching prefixes (p2)
	                        (iprange(p1.prefix) << iprange(p2.prefix) AND p1.indent BETWEEN p2.indent AND p2.indent + 0)
	                        OR
	                        -- Join in all neighbors (p1) of matching prefixes (p2)
	                        (true = true AND iprange(p1.prefix) << iprange(p2.display_prefix::cidr) AND p1.indent = p2.indent)
	                    )
	                )
	                -- set match conditions for p2
	                AND p2.id IN (
	                    SELECT inp.id FROM ip_net_plan AS inp JOIN ip_net_vrf AS vrf ON inp.vrf_id = vrf.id LEFT JOIN ip_net_pool AS pool ON inp.pool_id = pool.id
	                        WHERE  ( ( ( ( ( COALESCE(inp.comment, '') ~* ''  OR  COALESCE(inp.description, '') ~* '' )  OR  COALESCE(inp.node, '') ~* '' )  OR  COALESCE(inp.order_id, '') ~* '' )  OR  COALESCE(inp.customer_id, '') ~* '' )  AND  inp.indent = '0' )
	                    ORDER BY vrf_rt_order(vrf.rt) NULLS FIRST, prefix
	                    LIMIT 50
	                )
	            )
	            JOIN ip_net_vrf AS vrf ON (p1.vrf_id = vrf.id)
	            LEFT JOIN ip_net_pool AS pool ON (p1.pool_id = pool.id)
	            -- possible set where conditions, if we are doing a parent_prefix operation

	            ORDER BY vrf_rt_order(vrf.rt) NULLS FIRST, p1.prefix, CASE WHEN p1.prefix = p2.prefix THEN 0 ELSE 1 END OFFSET 0) AS a ORDER BY vrf_rt_order(vrf_rt) NULLS FIRST, prefix
2015-04-03 15:54:25 EEST [9268-3] nipap@nipap ERROR:  permission denied for relation ip_net_pool
2015-04-03 15:54:25 EEST [9268-4] nipap@nipap STATEMENT:  SELECT DISTINCT (po.id),
	                        po.id,
	                        po.name,
	                        po.description,
	                        po.default_type,
	                        po.ipv4_default_prefix_length,
	                        po.ipv6_default_prefix_length,
	                        po.member_prefixes_v4,
	                        po.member_prefixes_v6,
	                        po.used_prefixes_v4,
	                        po.used_prefixes_v6,
	                        po.free_prefixes_v4,
	                        po.free_prefixes_v6,
	                        po.total_prefixes_v4,
	                        po.total_prefixes_v6,
	                        po.total_addresses_v4,
	                        po.total_addresses_v6,
	                        po.used_addresses_v4,
	                        po.used_addresses_v6,
	                        po.free_addresses_v4,
	                        po.free_addresses_v6,
	                        po.tags,
	                        po.avps,
	                        vrf.id AS vrf_id,
	                        vrf.rt AS vrf_rt,
	                        vrf.name AS vrf_name,
	                        (SELECT array_agg(prefix::text) FROM (SELECT prefix FROM ip_net_plan WHERE pool_id=po.id ORDER BY prefix) AS a) AS prefixes
	                FROM ip_net_pool AS po
	                LEFT OUTER JOIN ip_net_plan AS inp ON (inp.pool_id = po.id)
	                LEFT OUTER JOIN ip_net_vrf AS vrf ON (vrf.id = inp.vrf_id) ORDER BY name
2015-04-03 15:54:25 EEST [9271-1] nipap@nipap ERROR:  permission denied for relation ip_net_pool
2015-04-03 15:54:25 EEST [9271-2] nipap@nipap STATEMENT:  SELECT DISTINCT (po.id),
	                        po.id,
	                        po.name,
	                        po.description,
	                        po.default_type,
	                        po.ipv4_default_prefix_length,
	                        po.ipv6_default_prefix_length,
	                        po.member_prefixes_v4,
	                        po.member_prefixes_v6,
	                        po.used_prefixes_v4,
	                        po.used_prefixes_v6,
	                        po.free_prefixes_v4,
	                        po.free_prefixes_v6,
	                        po.total_prefixes_v4,
	                        po.total_prefixes_v6,
	                        po.total_addresses_v4,
	                        po.total_addresses_v6,
	                        po.used_addresses_v4,
	                        po.used_addresses_v6,
	                        po.free_addresses_v4,
	                        po.free_addresses_v6,
	                        po.tags,
	                        po.avps,
	                        vrf.id AS vrf_id,
	                        vrf.rt AS vrf_rt,
	                        vrf.name AS vrf_name,
	                        (SELECT array_agg(prefix::text) FROM (SELECT prefix FROM ip_net_plan WHERE pool_id=po.id ORDER BY prefix) AS a) AS prefixes
	                FROM ip_net_pool AS po
	                LEFT OUTER JOIN ip_net_plan AS inp ON (inp.pool_id = po.id)
	                LEFT OUTER JOIN ip_net_vrf AS vrf ON (vrf.id = inp.vrf_id) ORDER BY name

**Comment by plajjan** [comment]
That's a long post :P

The database user that NIPAP is using to connect to PostgreSQL does not have sufficient permissions to access the tables.

I suppose this isn't on a Debian/Ubuntu system but another distribution, right? How did you go about setting up the database? I'm trying to update and improve the installation procedure for other distribution so any feedback is welcome.

The debian install scripts runs the following to set database permissions:
```
                    # grant necessary privileges on tables, views, sequences and functions to NIPAP db user
                    su -c "psql -q -d $DB_NAME -c 'GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public TO nipap'" postgres >/dev/null 2>&1
                    su -c "psql -q -d $DB_NAME -c 'GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA public TO nipap'" postgres >/dev/null 2>&1
                    su -c "psql -q -d $DB_NAME -c 'GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO $DB_USER'" postgres >/dev/null 2>&1
```

Hmpf, I just realized now that the last line probably should be a bit more restrictive. Anyway, the above should solev your issue.

**Comment by florinciprian** [comment]
Hello,

I have Debian, 

uname -a
Linux nipap 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux

I entered what you told me but still get that errors. I followed this: http://spritelink.github.io/NIPAP/docs/INSTALL.html, I selected to make the DB auto and after that I entered : 
psql -d nipap -f /usr/share/nipap/sql/ip_net.plsql
psql -d nipap -f /usr/share/nipap/sql/functions.plsql
psql -d nipap -f /usr/share/nipap/sql/triggers.plsql

Thank you.

**Comment by Arendtsen** [comment]
I do believe that the -U nipap (if that is user that is created for the
nipap database) is missing.
I did the same mistake.

/Martin

**Comment by florinciprian** [comment]
Hello,

psql -U nipap

psql: FATAL:  Peer authentication failed for user "nipap"

**Comment by florinciprian** [comment]
Hello,

How can I change the owner to be nipap?

nipap=# \dt
            List of relations
 Schema |    Name     | Type  |  Owner
--------+-------------+-------+----------
 public | ip_net_asn  | table | postgres
 public | ip_net_log  | table | postgres
 public | ip_net_plan | table | postgres
 public | ip_net_pool | table | postgres
 public | ip_net_vrf  | table | postgres
(5 rows)

nipap=# \dn
  List of schemas
  Name  |  Owner
--------+----------
 public | postgres

Thank you

**Comment by florinciprian** [comment]
I solved the problem,

GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public TO nipap;

**Comment by plajjan** [comment]
so you used the debian packages to install and you answered "yes" when it asked you to automatically setup the database? But it didn't actually setup the database?

**Comment by florinciprian** [comment]
Hello,

The database and the user were setup, but the user didn't had rights. I solved the problem:

GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public TO nipap;

**Comment by plajjan** [comment]
Yeah, but you said you ran these commands:
```
psql -d nipap -f /usr/share/nipap/sql/ip_net.plsql
psql -d nipap -f /usr/share/nipap/sql/functions.plsql
psql -d nipap -f /usr/share/nipap/sql/triggers.plsql
```

Which means that you added the tables.. not the debian script. After the Debian script ran, did you check if you had the tables or did you blindly run the above?

I don't know if you noticed, but on http://spritelink.github.io/NIPAP/docs/INSTALL.html there are two links. One for Debian systems and one for non-Debian Unix systems. The above commands are fetched from the non-debian version, which you probably shouldn't follow.

**Comment by plajjan** [comment]
I'm going to close this as there's no problem with NIPAP in itself.
