### ISSUE TITLE
LDAP not working - global name 'ldap' is not defined

### ISSUE THREAD

**Issue by alexrasmussendk** [SpriteLink/NIPAP#733]
Hi

When I setup NIPAP to LDAP authentication, I get the following error:
> WebApp Error: <type 'exceptions.NameError'>: global name 'ldap' is not defined

> Module nipapwww.controllers.auth:40 in login
>  if not auth.authenticate():
> Module nipap.authlib:344 in authenticate
>  except ldap.SERVER_DOWN as exc:
> NameError: global name 'ldap' is not defined

My NIPAP LDAP config is:
> [auth]
> default_backend = ldap                ; which backend to use by default
> auth_cache_timeout = 3600              ; seconds cached auth entries are stored
> 
> [auth.backends.local]
> type = SqliteAuth
> 
> db_path = /etc/nipap/local_auth.db     ; path to SQLite database used
> 
> [auth.backends.ldap]
> type = LdapAuth
> 
> basedn = dc=my,dc=domain,dc=com                ; base DN
> uri = ldap://dc1.my.domain.com            ; LDAP server URI
> 
> binddn_fmt = {}@my.domain.com 
> search = sAMAccountName={}
> 
> rw_group =
> ro_group =

I try to use NIPAP authentication with a Microsoft Active Directory Forest Functional Level: Windows Server 2008 R2.

What is wrong?

Thanks in advance.

**Comment by plajjan** [comment]
I think I introduced this bug when trying to do a late import of ldap. #726 will likely fix it.

Although there is a bug, I think this should work if you actually have the ldap module installed. Do you have python-ldap installed?

**Comment by alexrasmussendk** [comment]
Thanks, #726 solved the global name 'ldap' is not defined issue.
