### ISSUE TITLE
LDAP error: 000004DC: LdapErr: DSID-0C0906E8

### ISSUE THREAD

**Issue by alexrasmussendk** [SpriteLink/NIPAP#736]
Hi

I try to use NIPAP with LDAP authentication, but when I try to login with my Active Directory credentials I get the following error:

> Authentication error: {'info': '000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1', 'desc': 'Operations error'}

I only get the above error when I enter valid credentials. If I enter a valid user, but a incorrect password I get the following error: Invalid username or password.

So maybe NIPAP communicate with the Domain Controller, but then fail with something.

My NIPAP LDAP config is:
> [auth]
> default_backend = ldap                ; which backend to use by default
> auth_cache_timeout = 3600              ; seconds cached auth entries are stored
> 
> [auth.backends.local]
> type = SqliteAuth
> 
> db_path = /etc/nipap/local_auth.db     ; path to SQLite database used
> 
> [auth.backends.ldap]
> type = LdapAuth
> 
> basedn = dc=my,dc=domain,dc=com                ; base DN
> uri = ldap://dc1.my.domain.com            ; LDAP server URI
>tls = False                            ; initiate TLS, use ldap://
> 
> binddn_fmt = {}@my.domain.com 
> search = sAMAccountName={}
> 
> rw_group =
> ro_group =

I try to use NIPAP authentication with a Microsoft Active Directory Forest Functional Level: Windows Server 2008 R2.

I have python-ldap installed and NIPAP works fine with local authentication.

I have tried to set the following in: /etc/openldap/ldap.conf:
HOST DC1.my.domain.com
PORT 636
TLS_REQCERT demand

But it did not solve the error.

What is wrong?

Thanks in advance.

**Comment by alexrasmussendk** [comment]
I solved the error by adding OU to the basedn in nipap.conf.

Example: basedn = ou=users,dc=my,dc=domain,dc=com

**Comment by wreckoner** [comment]
Your solution fixed a somewhat unrelated problem for me!
