### ISSUE TITLE
Make view-command accept display prefix

### ISSUE THREAD

**Issue by garberg** [SpriteLink/NIPAP#738]
Today it's pretty annoying that host prefixes shown as result from the ```nipap address list ...``` command can not be copied and directly used with the ```nipap address view ...``` command as the former shows the display prefix attribute and the latter matches the prefix against the prefix attribute.  

One solution would be to let the view-command match its input against ```prefix or display_prefix```. Would that have any unwanted side-effects?

**Comment by plajjan** [comment]
Yes, for a /31 the first host has the same address as the network address, so prefix-length 31 vs 32 is the only way to differentiate between them. Obviously same for IPv6 /127.

This could potentially be a problem for any prefix length if someone has added a host with the same address as the network address.. but that would be illegal, it's only allowed for 31 & 127.

Perhaps check if address == network address and so special handling, like an error message or something?
