### ISSUE TITLE
last_modified attribute doesn't update on edits

### ISSUE THREAD

**Issue by toreanderson** [SpriteLink/NIPAP#749]
When creating a prefix, the stored `last_modified` attribute (and the `added` attribute) is initialised to the server time when the prefix was created. However, when later editing that prefix, the `last_modified` attribute doesn't change.

I am making an assumption here, namely that the `edit_prefix` caller isn't expected to manage the value of this attribute manually; the backend should do so automatically. I base this on the fact that it does get initialised automatically (i.e., I do not need to include it in the `attrs` struct I pass to `add_prefix`), and also the fact that the web interface doesn't even display this attribute (so the user simply cannot update it manually when making edits that way).

If the above assumption is wrong, then the bug is in the web interface (and my scripts...) for not explicitly updating `last_modified` when performing edits.

**Comment by plajjan** [comment]
You are right, the backend should handle it. I am fairly certain that it at least did at one point (when I introduced the change). I will look into it but could you please provide an example where it does not work?

There might be multiple SQL triggers involved.

**Comment by toreanderson** [comment]
One easy example would be to open an arbitrary pre-existing prefix for editing in the web interface, setting the description to `foobar`, and saving. You can then inspect the value of `last_modified` (can't use the web interface for that), and you'll see it's the same as `added` - it didn't get updated when the new description was saved.

**Comment by plajjan** [comment]
I think I introduced this bug when doing major refactoring of the SQL triggers and functions, see https://github.com/SpriteLink/NIPAP/commit/a8d5633bca55a51be12414e237e0b7fa6995f430

To avoid this in the future, I've added a test case that checks that the last_modified value has been updated for a trivial modification.
