### ISSUE TITLE
Database upgrade from 0.27.4 -> 0.28.0 gives an error but does upgrade the database

### ISSUE THREAD

**Issue by Arendtsen** [SpriteLink/NIPAP#759]
The output is:

martin@db02:~/sql % psql -U nipap -d nipap < upgrade-5-6.plsql
ALTER TABLE
DROP INDEX
CREATE INDEX
ERROR:  cannot drop index ip_net_pool_name_key because constraint ip_net_pool_name_key on table ip_net_pool requires it
HINT:  You can drop constraint ip_net_pool_name_key on table ip_net_pool instead.
ERROR:  relation "ip_net_pool__name__index" already exists
COMMENT

**Comment by plajjan** [comment]
Can you try to manually run the two comands on line 9 and 10 in this file https://github.com/plajjan/NIPAP/blob/sql-fix/nipap/sql/upgrade-5-6.plsql

And then do "\d ip_net_pool" and paste the output here?

**Comment by plajjan** [comment]
This should be fixed by acd24290689d729a7a6fde1b05f47fef92c492af. Closing.
