### ISSUE TITLE
RT field loses dotted quad format

### ISSUE THREAD

**Issue by awaddell** [SpriteLink/NIPAP#767]
Hi, after installing on Ubuntu 14.04.2 LTS with Debian instructions, the RT field always (CLI/WEB) loses it's (IPv4) dotted-quad format.

nipap vrf add rt 192.168.0.0:1 name TEST
Added VRF 'TEST' [RT: 3232235520:1]

I've since run the SQL install scripts manually per the generic 'Nix instructions to no avail.

**Comment by plajjan** [comment]
You are correct.. culprit is https://github.com/SpriteLink/NIPAP/blob/master/nipap/sql/triggers.plsql#L49 introduced in 55cc418a13ee9d07b90f31f4b6390dc9f7952894. That was introduced to avoid problems around uniqueness RTs, see #249 for details.

Obviously it does the wrong thing..

**Comment by plajjan** [comment]
Should add a test case for this as well!
