### ISSUE TITLE
Allow network and broadcast IP's to be usable

### ISSUE THREAD

**Issue by CrackerJackMack** [SpriteLink/NIPAP#798]
In some cases (such as loopbacks and /31's) it would be nice to be able to designate that an assignment is "fully usable".  I don't know if it needs to be another type or another flag or sorts but it could be rather handy when using prefix from prefix API calls.

**Comment by plajjan** [comment]
I don't really understand. When doing from-prefix or from-pool operations the find_free_prefix function normally avoids handing out the network and broadcast address but it makes an exception for /31 and /127 networks (see https://github.com/SpriteLink/NIPAP/blob/master/nipap/sql/functions.plsql#L440). For /32 assignments (like a loopback) there's not much to be done either way.

Can you elaborate on what it is you need this for? Ie, what is currently not covered?

**Comment by CrackerJackMack** [comment]
Use case: If you assign a /27 for loopbacks you want to be able to use all the available IP's in that block

Use case: You assign a /24 for anycasting (advertising the summary only externally, only accepting /32's internally) you want the whole /24 available, even if you carved it up into smaller groupings of /29's to hand out to specific teams or projects.

I could probably come up with a few more if need be.

**Comment by plajjan** [comment]
No no, I don't need more examples.. one is enough :)

I get it and you are right, we should only avoid network+broadcast in an assignment but not in a reservation. As discussed over IRC, your current use of type "host" for loopbacks is probably incorrect and a from-prefix operation on an "assignment" to get a new host will always return the first usable address, i.e. not network or broadcast.
