### ISSUE TITLE
centos install

### ISSUE THREAD

**Issue by rowco** [SpriteLink/NIPAP#802]
Hi, Attempting to install on CentOS 6.6.

Getting the following error:

[root@geoff nipap]# python ./setup.py install
nipap-passwd.man.rst:53: (ERROR/3) Unexpected indentation.
nipap-passwd.man.rst:54: (WARNING/2) Inline emphasis start-string without end-string.
running install
running build
running build_py
running install_lib
byte-compiling /usr/lib/python2.6/site-packages/nipap/backend.py to backend.pyc
SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/nipap/backend.py', 311, 23, "_pool_attrs = {k: v for k, v in _pool_spec.iteritems() if not _pool_spec[k]['ro']}\n"))

running install_data
copying nipapd.8 -> /usr/share/man/man8/
copying nipap-passwd.1 -> /usr/share/man/man1/
running install_egg_info
Removing /usr/lib/python2.6/site-packages/nipap-0.28.3-py2.6.egg-info
Writing /usr/lib/python2.6/site-packages/nipap-0.28.3-py2.6.egg-info

Looks like a python version issue. I can't find any documentation saying the python 2.6 isn't supported.

Any suggestions (short of installing a different python version)?

Thanks.

**Comment by plajjan** [comment]
It's not abundantly clear which version of python we depend on, but yeah, you do need 2.7, so please try with that.

I should warn you that setting up on CentOS is fairly untested and might be difficult but we'll try to help out as best we can :)

**Comment by pheller** [comment]
Python2.7 on centos is most easily installed via the software collections.

See here for more info:

http://wiki.centos.org/AdditionalResources/Repositories/SCL

Regards,
  Phil

**Comment by plajjan** [comment]
While we are on the topic of CentOS packages, how would I go about installing the other packages that nipapd depends on? 
* python
* python-psycopg2
* postgresql (>=9.1)
* postgresql-9.1-ip4r (>= 2.0)
* postgresql-contrib
* python-flask
* python-flask-xml-rpc
* python-flask-compress
* python-tornado
* python-parsedatetime
* python-tz
* python-dateutil
* python-psutil

I don't have much experience with third party software repos on CentOS, in fact I don't have much experience with CentOS at all... @pheller any pointers? :)
If we can find the above packages we might be able to package .rpm files for nipap...

**Comment by emjemj** [comment]
The following packages should be installed
* python is in base -  (yum is written in python)
* postgresql, postgresql-server - (9.2 in RHEL/CentOS 7)
* ip4r doesn't seem to be in default repos
* postgresql-contrib

Some of the python packages seem to exist, not sure about packaging details though.

**Comment by plajjan** [comment]
Are there third party repositories for things like ip4r and more python packages? It seems really painful if we have to start building RPMs for a number of packages that we depend on.

**Comment by rowco** [comment]
Firstly, I've been really impressed with the comments so far, nice to have some useful feedback.

I managed to install all of the dependencies, by having nothing more that the postgres yum repository installed. But, it is the python2.7 dependency that is causing most of the problems. I managed to install it using the software collections repo as suggested, but then you need to install 2.7 versions of the modules with pip. Not really the way that I had hoped to manage this system.

I believe centos 7 has a newer version of python, I'll see if I can give this a go.

**Comment by plajjan** [comment]
What packages where you able to get as rpm and from which repo?

We do build debs for some dependencies so I guess it's no more than fair that we also build rpm of those. Like flask compress, parsedatetime and some others...

**Comment by staffordrau** [comment]
I've been almost successful getting NIPAP to run on CentOS 7. I'm close, but stuck on getting nipapd to start:

Sep  9 09:50:09 CentOS7 systemd: Starting NIPAP IPAM Service...
Sep  9 09:50:09 CentOS7 systemd: Started NIPAP IPAM Service.
Sep  9 09:50:10 CentOS7 nipapd: Error checking version of Sqlite database for local auth: No 'user' table.
Sep  9 09:50:10 CentOS7 systemd: nipapd.service: main process exited, code=exited, status=1/FAILURE
Sep  9 09:50:10 CentOS7 systemd: Unit nipapd.service entered failed state.

In /etc/nipap/nipap.conf I have the following:
[auth]
default_backend = local 

[auth.backends.local]
type = SqliteAuth
db_path = /etc/nipap/local_auth.db 

The file /etc/nipap/local_auth.db exists, but is empty. Did I miss part of the install process that should have created the sqlite user table?

**Comment by plajjan** [comment]
When you say /etc/nipap/local_auth.db is empty, do you mean 0 bytes?

The local auth db is created by the debian postinst script, see https://github.com/SpriteLink/NIPAP/blob/master/nipap/debian/nipapd.postinst#L132

**Comment by staffordrau** [comment]
Yes, 0 bytes - 

[srau@CentOS7 ~]$ ls -l /etc/nipap
total 16
-rw-r--r--. 1 root root    0 Sep  4 14:24 local_auth.db
-rw-r--r--. 1 root root 7115 Sep  3 08:39 nipap.conf
-rw-rw-r--. 1 root root 7111 Sep  1 16:46 nipap.conf.dist

As this is a CentOS install, I'll take a look at what the debian postinst script does and try to recreate it.

Thanks!

**Comment by staffordrau** [comment]
Seems that it was as simple as running /usr/sbin/nipap-passwd create-database.

I have some more dependencies to sort out, but I think I'm close to getting this running on CentOS 7.

**Comment by plajjan** [comment]
@staffordrau yes, you just need to run nipap-passwd create-database to create. Per default it looks for a configuration file in /etc/nipap/nipap.conf and then reads out the location of the local auth db from the config, so it knows where to create it.

**Comment by agebel** [comment]
@staffordrau: did you ever get this running on CentOS 7? I've just gotten it running by synthesizing a couple of external documentation sources and the NIPAP documentation plus some issues. 

I'm thinking of trying to build an RPM, and would be interested to know whether you had any success, what your complications were and whether you've considered packaging this for CentOS 7.

**Comment by plajjan** [comment]
@agebel have you seen http://blog.mean.net/installing-nipap-on-redhat-centos/ and http://blog.mean.net/nipap-web-frontend-on-centos-redhat/ ?

I'd be really interested in PR for RPM support :)

**Comment by tiago-cruz-movile** [comment]
@staffordrau, nice tip worked here running CentOS 7:

```
[root@nipap ~]# ll /etc/nipap/local_auth.db
-rw-r--r-- 1 root root 0 Jun 14 14:26 /etc/nipap/local_auth.db
[root@nipap ~]# nipap-passwd --create-database
[root@nipap ~]# ll /etc/nipap/local_auth.db
-rw-r--r-- 1 root root 3.1k Jun 14 16:52 /etc/nipap/local_auth.db
```

Can you please add this to documentation?
 - http://spritelink.github.io/NIPAP/docs/install-unix.html

Thanks!!

**Comment by plajjan** [comment]
Ok closing this one since there's not much activity.
