### ISSUE TITLE
whoisd doesn't work with entries using umlaut/accent characters

### ISSUE THREAD

**Issue by GarryG** [SpriteLink/NIPAP#808]
While using special characters like German Umlauts (äöüß) on both the web interface as well as the command line tool works fine, using the whois interface fails for any entry using them. And that not only when trying to search for an umlaut string itself, but also a prefix containing such a character in its description. e.g.:

root@ipam1:~# nipap address list 192.168.10.128/29
Searching for prefixes in any VRF...
VRF            Prefix                                     #  Node                Order          Customer       Description
==========================================================================================================================
-              192.168.0.0/16                           R -  None                None           None           NETHINKS PA /16
-                192.168.0.0/20                         R -  None                None           None           None
-                  192.168.10.0/24                      R -  None                None           None           None
-                    192.168.10.128/29                  A -  None                None           15641          Günther (aDSL)
-                      192.168.10.129/29                H -  None                None           None           None
root@ipam1:~# nipap address list Günther
Searching for prefixes in any VRF...
VRF            Prefix                                   #  Node                Order          Customer       Description
========================================================================================================================
-              192.168.0.0/16                         R -  None                None           None           NETHINKS PA /16
-                192.168.0.0/20                       R -  None                None           None           None
-                  192.168.10.0/24                    R -  None                None           None           None
-                    192.168.10.128/29                A -  None                None           15641          Günther (aDSL)
-                192.168.32.0/19                      R -  None                None           None           None
-                  192.168.41.0/24                    R -  None                None           None           None
-                    192.168.41.144/28                A -  None                None           15641          Günther EVPN 4M

But:
root@ipam1:~# whois -hlocalhost 192.168.10.128/29
root@ipam1:~# whois -hlocalhost 192.168.10.128/24
root@ipam1:~# whois -hlocalhost 192.168.10.0/24
root@ipam1:~# whois -hlocalhost 192.168.10.0
% This is the NIPAP whois query service.

inetnum:             192.168.0.0/16
vrf-name:            default
descr:               NETHINKS PA /16
country:             DE
monitor:             False

inetnum:             192.168.0.0/20
vrf-name:            default
monitor:             False

inetnum:             192.168.10.0/24
vrf-name:            default
monitor:             False

inetnum:             192.168.10.0/29
vrf-name:            default
descr:               EVPN XXX
country:             DE
monitor:             False

% This query was served by the NIPAP whois server version 0.27.3

Please note that not only the affected entry isn't output, but rather ALL the lines, so I assume the whois daemon seems to have some sort of internal exception ...

**Comment by plajjan** [comment]
First thing that comes to mind is that the whois protocol only allows for us-ascii so there is no way we can support this in a standardized way AFAIK.

**Comment by GarryG** [comment]
If that is the cause, what about converting or dropping non-ASCII characters from the results returned by the whosid ?

**Comment by plajjan** [comment]
That is indeed one possibility. Another one is to simply assume UTF-8 encoding in both queries and responses. It seems there are a few other implementations that do that already.

Maybe we can look at how various whois clients format their request when a non ascii character is used...

**Comment by plajjan** [comment]
The whois client on Ubuntu will encode a request with IDNA if it detects non ASCII characters, so "åäö" becomes "xn--4cab6c". We can rather easily decode that.

If I look at the response from whois.nic.se for "räksmörgås.se" (a Swedish test domain for IDN) it returns the result as UTF-8, as seen here with ngrep:
```
T 2a00:801:f0:10f::165:43 -> 2001:470:df70::6427:d9a4:3b56:9c01:53771 [AP]
  64 6f 6d 61 69 6e 3a 20    20 20 20 20 20 20 20 20    domain:
  20 20 78 6e 2d 2d 72 6b    73 6d 72 67 73 2d 35 77      xn--rksmrgs-5w
  61 6f 31 6f 2e 73 65 20    28 72 c3 a4 6b 73 6d c3    ao1o.se (r..ksm.
  b6 72 67 c3 a5 73 2e 73    65 29 0d 0a                .rg..s.se)..
```
The line first contains the IDN encoded domain and then in parentheses we have UTF-8, for example "ö" which is on the third line is encoded as 6d c3, which is UTF-8 for "ö".

I have no problem with implementing the same scheme, i.e. we accept IDN encoded strings and return UTF-8.
