### ISSUE TITLE
Read password from stdin instead of .nipaprc

### ISSUE THREAD

**Issue by ISharkI** [SpriteLink/NIPAP#838]
Hello together

Even if the webinterface is really great I'm kinda the CLI-Guy. I tested it and like it - besides that part about storing your password clear text in an file. 

If you're using the LDAP-Backend you're most likeley having several systems you have access to. And you don't want to give the server admin(s) or some botnet the opportunity to steal your password and gain more systems.

Therefore I'd like to add a feature request: Instead of exiting with an error if "password" is not found at .nipaprc give the user a prompt (e.g. using "getpass") and only raise the exception if thats also not provided.

**Comment by plajjan** [comment]
Fair enough. I'm certainly well aware not everyone fancies storing a password in a clear text (I don't either).. guess the long term solution would be some form of tokens instead so we can still store it for convenience but it doesn't grant access to anything else.

Would you also like to have a shot at implementing it? Should be a fairly small patch :)

**Comment by ISharkI** [comment]
Well it's not fancy looking but it's working. See pull request #839

**Comment by plajjan** [comment]
Fixed through merge of #950.
