### ISSUE TITLE
Error in webpage instructions

### ISSUE THREAD

**Issue by hallinde** [SpriteLink/NIPAP#851]
On page http://spritelink.github.io/NIPAP/docs/config-www.html
it says 
nipap-passwd add --username myuser --password mypassword --name "my user"

However I got this, 
someone@somewhere:/home/someone# nipap-passwd add --username jim --password jim --name "Jim"
usage: nipap-passwd [-h] [-u USER] [-p PASSWORD] [-n NAME] [-t] [-r]
                    [-f DB_FILE] [-c CONFIG] [--version]
                    [{list, add, delete, test-user, latest-version, create-database, upgrade-database}]
nipap-passwd: error: unrecognized arguments: --username jim

**Comment by plajjan** [comment]
Fixed through merge of #852. It is now consistent.
