### ISSUE TITLE
When adding an empty AVP to the extra-attributes in the web gui, the empty key gets stored in database

### ISSUE THREAD

**Issue by emjemj** [SpriteLink/NIPAP#858]
To reproduce;
1. Click the add-attribute under extra attributes on the prefix edit page
2. Click save without adding attribute or value.
3. Go to prefix edit page again, the empty attribute is still there.

Empty attributes should be ignored and not saved to database.

**Comment by plajjan** [comment]
I think this is fixed through #883, which is included in v0.29.0 that's available in testing, can you please confirm that it's fixed?

**Comment by plajjan** [comment]
If not by #883 this is fixed by #1018. Closing.
