### ISSUE TITLE
Pynipap extra query search options for vrf_id returns responses from more than one vrf_id

### ISSUE THREAD

**Issue by hallinde** [SpriteLink/NIPAP#864]
To shed some light on pynipap smart_searching within a certain vrf
In [622]:oldvrf_query = { 'operator': 'equals', 'val1': 'vrf_id', 'val2': '19707' }
In [623]:oldlist = Prefix.smart_search('10.156.158.0/23',{'extra_query' : oldvrf_query,'max_result':512})
In [624]: set([i.vrf.id for i in oldlist['result']])
Out[624]: {0, 19707, 19708}

In [636]: oldlist['search_options']
Out[636]:
{'children_depth': 0,
 'extra_query': {'operator': 'equals', 'val1': 'vrf_id', 'val2': '19707'},
 'include_all_children': False, 'include_all_parents': False, 'include_neighbors': False,
 'max_result': 512, 'offset': 0,  'parent_prefix': None, 'parents_depth': 0}

According to documentation
"vrf_id - ID of the VRF which the prefix belongs to." should be a viable search option
When I specify a certain id I expect to get result with only that id, how come I get responses from default and 19708 aswell?

**Comment by plajjan** [comment]
You are calling the function incorrectly. You likely want:
```
oldvrf_query = { 'operator': 'equals', 'val1': 'vrf_id', 'val2': '19707' }
Prefix.smart_search('10.156.158.0/23', extra_query = oldvrf_query, search_options { 'max_result':512})
```

Were you per any chance looking at the API docs? The pynipap lib provides language bindings which often make a bit more sense but it looks different from how the raw API function is called.

**Comment by hallinde** [comment]
Thank you for clearifying what I did wrong 
Most likely I checked the documentation for another smart_search in the API yes since pynipap search docs are yet missing #712

**Comment by plajjan** [comment]
Right. So I'm going to go close this now. Feel free to reopen or open new issue should you have more questions :)

**Comment by plajjan** [comment]
Btw, it's not missing, it's just sparse - http://nipap.readthedocs.org/en/v0.28.4/pynipap.html#pynipap.Prefix.smart_search

**Comment by plajjan** [comment]
XML-RPC doesn't have named arguments, it only does positional arguments, so the way we solve this is by only having one positional argument, which is a dict, and then we pass parameters in there thereby emulating named arguments. This is why the API docs for smart_search says it takes one dict (because it does) and that would look like more similar to what you were trying to do.
