### ISSUE TITLE
is it possible to have prefix for URL

### ISSUE THREAD

**Issue by nvitaly** [SpriteLink/NIPAP#868]
For example I want nipap URL to be http://myserver/nipap

Thank you

**Comment by plajjan** [comment]
I'm not sure if this is actually supported. You could try changing your Apache config to serve it off /nipap instead but I'm afraid that we might not be using relative URLs so it might break :/

**Comment by plajjan** [comment]
I'll be closing this issue. I don't see that it's important to support custom paths as it's so easy to setup virtual hosts.
