### ISSUE TITLE
pynipap deb package doesn't support python3

### ISSUE THREAD

**Issue by LordAro** [SpriteLink/NIPAP#875]
pynipap is compatible with python3, but the debian package only does python2

**Comment by plajjan** [comment]
Ok, you want a python3-pynipap package, right?

**Comment by LordAro** [comment]
Pretty much, yeah :)

Installing via pip gets me a pynipap module for py2 & py3, no reason why there shouldn't be an equivalent deb package

( http://www.wefearchange.org/2012/01/debian-package-for-python-2-and-3.html looks to be fairly useful, depending on how knowledgeable you are about debian packaging)

**Comment by plajjan** [comment]
Yeah, there's no reason in particular that we haven't created such a package. I think it's more than we (or I) envisioned that we get py3 compatibility and then release packages for both py2 and py3 but as we still have some more work on the other components for full py3 compatibility we never released the packages.

Nothing stops us from handling pynipap separately.

**Comment by plajjan** [comment]
Okay, wasn't quite as easy as I imagined. https://github.com/SpriteLink/NIPAP/blob/master/pynipap/debian/rules says python2. Can't just change or add python3 because that won't produce any working package. How do we actually tell it to build both py2 and py3? @garberg ideas?

PRs accepted :)
