### ISSUE TITLE
Login via LDAPauth fails if givenName has unicode characters

### ISSUE THREAD

**Issue by Eising** [SpriteLink/NIPAP#884]
If a user has a unicode character in his given name, the log in fails with the following error:

Error - <type 'exceptions.UnicodeDecodeError'>: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)

I suspect that the error happens on authlib.py:396

```python
395             res = search_conn.search_s(self._ldap_basedn, ldap.SCOPE_SUBTREE, self._ldap_search.format(ldap.dn.escape_dn_chars(self.username)), ['cn','memberOf'])
396             self.full_name = res[0][1]['cn'][0]
```

**Comment by garberg** [comment]
This sounds pretty similar to #922, can you please verify whether it's been fixed in v0.29.0 (which is in the testing repo)?

**Comment by plajjan** [comment]
@Eising can you plxz test if this is still an issue with v0.29.0 from testing? :)

**Comment by Eising** [comment]
I've recently built nipapd from master, and the issue is solved there at least.

**Comment by plajjan** [comment]
Ok, good. Closing.
