### ISSUE TITLE
error in the install documentation

### ISSUE THREAD

**Issue by Haiironokumo** [SpriteLink/NIPAP#889]
I'm trying to install nipap, in this page :  NIPAP/docs/config-www.rst the optio --username is used but it doesn't exist.

The correct option is --user.

Can you corrected it for future users.

Thx

**Comment by plajjan** [comment]
Hehe, le funny. So yes, there is a discrepancy between documentation and 0.28.4 but nipap-passwd in git master (https://github.com/SpriteLink/NIPAP/blob/master/nipap/nipap-passwd#L23) have the --username option so this will be fixed once we release 0.29 :)

**Comment by Haiironokumo** [comment]
Ok, thx.

2016-02-16 15:46 GMT+01:00 Kristian Larsson <notifications@github.com>:

> Hehe, le funny. So yes, there is a discrepancy between documentation and
> 0.28.4 but nipap-passwd in git master (
> https://github.com/SpriteLink/NIPAP/blob/master/nipap/nipap-passwd#L23)
> have the --username option so this will be fixed once we release 0.29 :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpriteLink/NIPAP/issues/889#issuecomment-184708514>.
>



-- 
Michaël
