### ISSUE TITLE
nipapd psutil - AttributeError: 'Process' object has no attribute 'get_children'

### ISSUE THREAD

**Issue by 2tg67eHE4xWE** [SpriteLink/NIPAP#901]
This is function invalid in psutil docs, it was resolved by changing:
for pid in p.get_children(recursive=True):

simply to:

for pid in p.children(recursive=True):

Easy fix I think :)

**Comment by plajjan** [comment]
For what version of psutil is this? What is your environment? OS? Python version?

We need to make sure that such a change doesn't break other systems.

**Comment by 2tg67eHE4xWE** [comment]
I'm using the new version of psutil (4.1.0) but this was dropped back in version 2.0.0 according to the release notes, this should be agnostic to the other variables. But just for info it's python 2.7, Centos 7 not sure what you're asking for when you say environment though, if you clarify I'd be happy to answer.

**Comment by plajjan** [comment]
It's likely not dropped in 2.0.0 as Debian stable is using python-psutil 2.1.1 and there are numerous deployments on debian.

We've had psutil version compatibility issues before. Don't remember from the top of my head what they were... will have a look though.

Regardless, could you whip up a pull request with the change?

**Comment by plajjan** [comment]
Okay the other I was thinking of was #760 fixed by #768. It wasn't really a version problem.. anyway, submit a PR and I'll merge!
