### ISSUE TITLE
NIPAP on Ubuntu 16.04

### ISSUE THREAD

**Issue by bertjwregeer** [SpriteLink/NIPAP#908]
I am trying to install NIPAP, and I am using Ubuntu 16.04. It doesn't currently install with:

```
apt-get install nipapd
```

Error message:

```
root@ubuntu1604:/home/bregeer# apt-get install nipapd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nipapd : Depends: postgresql-9.1-ip4r (>= 2.0) but it is not going to be installed or
                   postgresql-9.3-ip4r (>= 2.0) but it is not installable or
                   postgresql-9.4-ip4r (>= 2.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Unfortunately none of those PostgreSQL versions are available, with the release being offered by Ubuntu being PostgreSQL 9.5

**Comment by plajjan** [comment]
This is actually fixed already - see #894. Will package 0.29 up shortly for release!

**Comment by GustavRanz** [comment]
This is still not fixed, as current version as to your documented way of installation is 0.28.4-1 which is still requiring postgresql:

nipapd : Depends: postgresql-9.1-ip4r (>= 2.0) but it is not going to be installed or
                   postgresql-9.3-ip4r (>= 2.0) but it is not installable or
                   postgresql-9.4-ip4r (>= 2.0) but it is not installable

Please reopen issue until fixed.

**Comment by garberg** [comment]
Now v0.29 is available in the testing repo, could you please verify that this issue has been adressed?

**Comment by Chee-tos** [comment]
I just triy in my Debian 8.5 and return the dependency error! Could you help me? Thank you.

root@debian-office:~# apt-get install nipapd
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nipapd : Depends: nipap-common but it is not going to be installed
          Depends: python-psycopg2 but it is not installable
          Depends: postgresql (>= 9.1) but it is not installable or
                   postgresql-9.1 but it is not installable or
                   postgresql-9.2 but it is not installable or
                   postgresql-9.3 but it is not installable or
                   postgresql-9.4 but it is not installable
          Depends: postgresql-9.1-ip4r (>= 2.0) but it is not going to be installed or
                   postgresql-9.3-ip4r (>= 2.0) but it is not installable or
                   postgresql-9.4-ip4r (>= 2.0) but it is not installable
          Depends: postgresql-contrib but it is not installable or
                   postgresql-contrib-9.3 but it is not installable
          Depends: python-flask but it is not installable
          Depends: python-flask-xml-rpc but it is not going to be installed
          Depends: python-flask-compress but it is not going to be installed
          Depends: python-tornado but it is not installable
          Depends: python-parsedatetime but it is not installable
          Depends: python-tz but it is not installable
          Depends: python-dateutil but it is not installable
          Depends: python-psutil but it is not installable
E: Unable to correct problems, you have held broken packages.
root@debian-office:~#

**Comment by evpretorious** [comment]
The problem persists for users of ubuntu-16.04.1-server:

> root@nipap:~# apt-get install nipapd
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  nipapd : Depends: postgresql-9.1-ip4r (>= 2.0) but it is not going to be installed or
>                    postgresql-9.3-ip4r (>= 2.0) but it is not installable or
>                    postgresql-9.4-ip4r (>= 2.0) but it is not installable
> E: Unable to correct problems, you have held broken packages.
> 
> root@nipap:~# apt-cache search ip4r
> postgresql-9.5-ip4r - IPv4 and IPv6 types for PostgreSQL 9.5
> postgresql-9.1-ip4r - IPv4 and IPv6 types for PostgreSQL 9.1
> 
> root@nipap:~# apt-cache search postgresql-9.1
> postgresql-9.1-ip4r - IPv4 and IPv6 types for PostgreSQL 9.1
> 
> root@nipap:~# apt-get install postgresql-9.1-ip4r
> ...
> The following packages have unmet dependencies:
>  postgresql-9.1-ip4r : Depends: postgresql-9.1 but it is not installable
> E: Unable to correct problems, you have held broken packages.

Please re-open this issue!
