### ISSUE TITLE
Feature request: let whoisd run in foreground

### ISSUE THREAD

**Issue by alchuk** [SpriteLink/NIPAP#920]
I'm running nipapd under Gentoo. Since Gentoo is not supported here and there are no openrc init scripts, I prefer NIPAP daemons to be started by supervisord, which in turn can run them in foreground saving STDOUT output to a separated log. Whoisd lacks an option for it, so I'd like to ask you to implement it. 
Thanks in advance

**Comment by plajjan** [comment]
Would you like to have a go at it yourself? :)

It's just a matter of changing https://github.com/SpriteLink/NIPAP/blob/master/whoisd/nipap-whoisd#L210 to look roughly like https://github.com/SpriteLink/NIPAP/blob/master/nipap/nipapd#L197  and you need to add argument for --foreground

**Comment by alchuk** [comment]
yeah, in my local whoisd i've commented out createDaemon, but there's more work to do: server.serve_forever() doesn't like abrupt interruption.
as I'm not much into python, I wouldn't dirty your project ((:
