### ISSUE TITLE
nipapd postgresql dependency (link to  NIPAP on Ubuntu 16.04 #908)

### ISSUE THREAD

**Issue by GustavRanz** [SpriteLink/NIPAP#923]
Can someone please update the debian packages? The documented installation still results in version 28.4-1 being retrieved which depends on old postgresql not available on current LTS ubuntu:

Package: nipapd
Versions:
0.28.4-1 (/var/lib/apt/lists/spritelink.github.io_NIPAP_repos_apt_dists_stable_main_binary-i386_Packages)
 Description Language:
                 File: /var/lib/apt/lists/spritelink.github.io_NIPAP_repos_apt_dists_stable_main_binary-i386_Packages
                  MD5: 8211a2a377e6606ba3f9c3d36c67deb7

nipapd : Depends: postgresql-9.1-ip4r (>= 2.0) but it is not going to be installed or
                   postgresql-9.3-ip4r (>= 2.0) but it is not installable or
                   postgresql-9.4-ip4r (>= 2.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

Please reopen issue #908 until fixed.

Thank you!

**Comment by plajjan** [comment]
Sorry for late feedback - I missed this one. I think the recommendation here is simply to move to 0.29, which is currently in testing. I do get that it's an inconvenience while it's still not marked as stable but we just don't have the man power to backport, test and package old maintenance releases.

0.29.2 is turning out rather well, can you give that a go? :)

**Comment by plajjan** [comment]
Going to close this one. Won't be updated 0.28 - go with 0.29 - it will be in stable rather shortly.

**Comment by evpretorious** [comment]
Please re-open this issue - The problem persists for users of ubuntu-16.04.1-server:

> root@nipap:~# apt-get install nipapd
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  nipapd : Depends: postgresql-9.1-ip4r (>= 2.0) but it is not going to be installed or
>                    postgresql-9.3-ip4r (>= 2.0) but it is not installable or
>                    postgresql-9.4-ip4r (>= 2.0) but it is not installable
> E: Unable to correct problems, you have held broken packages.
