### ISSUE TITLE
Question: Searching for free subnet

### ISSUE THREAD

**Issue by alanwill** [SpriteLink/NIPAP#940]
I'm looking for an IPAM solution that would manage a /8 network and allow us to programmatically request an unassigned /20 or /24. Is this something that NIPAP can do? I saw from the docs that there's the ability to search for a pool or prefix but I'm not sure if you can search for a free/unassigned prefix or pool. Is this doable?

**Comment by plajjan** [comment]
Yes, that is possible. What you usually do is not to "search for a free prefix" but rather "ask for a prefix of size X", which internally is handled by first finding free prefixes and then allocating the first one. If you really would like to find free prefixes then you can call the find_free_prefix() via the API.

If you are using python and the pynipap lib it would be something like (not tested):
```python
# add our big network
big_network = Prefix()
big_network.prefix = "10.0.0.0/8"
big_network.description = "My big network"
big_network.type = "reservation"
big_network.save()

# look for the 10 next available /24s and print to screen
for p in Prefix.find_free(vrf = None, args = {'from-prefix': '10.0.0.0/8', 'prefix_length': 24, 'count': 10 }):
    print "Free prefix:", p

# allocate first available /24 from 10.0.0.0/8
new_prefix = Prefix()
new_prefix.description = "My new network"
new_prefix.type = "assignment"
# the save will communicate with the backend and ask for the next available /24
new_prefix.save({ 'from-prefix': '10.0.0.0/8', 'prefix_length': 24 })
# we can now read the assigned prefix from the new_prefix object
print "We got prefix:", new_prefix.prefix
```
also see the boilerplate.py for doing initial stuff like setting up the API connection.

**Comment by plajjan** [comment]
I think I've answered your question so I am going to go ahead and close this issue. Feel free to re-open or open a new issue if you have further issues. Also, there's #NIPAP on the Freenode IRC network where you can also ask questions with a bit more interactive responses :)

**Comment by alanwill** [comment]
Thanks @plajjan the above works great. Took me a while to get it setup and working but it does and just what I needed. Really appreciate your help on this!

**Comment by plajjan** [comment]
@alanwill did you see boilerplate.py ? It'll help you get the structure right of your program.. or show an example of how it can be done at least :)

**Comment by alanwill** [comment]
@plajjan I already have it working but where is boilerplate.py (don't see it in the repo)

**Comment by plajjan** [comment]
https://github.com/SpriteLink/NIPAP/blob/master/utilities/boilerplate.py
