### ISSUE TITLE
NIPAP  postgresql-9.5-ip4r

### ISSUE THREAD

**Issue by outarabf** [SpriteLink/NIPAP#994]
HI there,

i have an issue when installing NIPAP with  postgresql version, is the issue solved or not?

apt-get install nipapd
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nipapd : Depends: postgresql-9.1-ip4r (>= 2.0) but it is not going to be installed or
                   postgresql-9.3-ip4r (>= 2.0) but it is not installable or
                   postgresql-9.4-ip4r (>= 2.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by plajjan** [comment]
The current stable NIPAP version, 0.28.4, was built in a time when postgresl 9.4 was probably the latest release. You are now trying to install it on a more modern platform and so you have a newer version of postgres.

NIPAP 0.29 is in the testing repo and will end up in stable quite soon. I would recommend that you try to use it instead.

**Comment by outarabf** [comment]
noted,

is have downgrade my postgresql version to 9.4.
