### ISSUE TITLE
Prefix search_options returns Null

### ISSUE THREAD

**Issue by psyc0** [SpriteLink/NIPAP#998]
in pynipap using Prefix.search:

when doing a search query without specifying any search_option, the returning search_option is {'include_all_children': False, 'max_result': 50, 'include_neighbors': False, 'parent_prefix': None, 'include_all_parents': False, 'parents_depth': 0, 'offset': 0, 'children_depth': 0}

when trying to reuse this dict in a new search it raises Nonetype error (probably to the fact that parent_prefix is 'None':
    prefixes = Prefix.search(query, search_options)
  File "/usr/lib/python2.7/dist-packages/pynipap.py", line 936, in search
    raise _fault_to_exception(xml_fault)
pynipap.NipapError: <type 'exceptions.TypeError'>:int() argument must be a string or a number, not 'NoneType'

**Comment by plajjan** [comment]
Yupp, I agree with your assessment. The question is if we really support the case of feeding back the search_options as returned. If you don't want to search with parent_prefix, then why include it at all?

The code can of course be modified to not do anything if parent_prefix=None. That would require some modification around https://github.com/SpriteLink/NIPAP/blob/master/nipap/nipap/backend.py#L3386

**Comment by psyc0** [comment]
true, got the idea from @garberg when trying some query and hit this, so just wanted to report, but you are correct.. either not do anything or maybe throw an exception pointing to that option being incorrect.
